### ISSUE TITLE
1k Issue Party

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#1000]
- [x] Plan a 1k Issue party
- [x] Execute a 1k Issue Party
- [ ] Close the 1k'th issue

**Comment by joshhting** [comment]
We should discuss this today

**Comment by joshhting** [comment]
Option 1: Rocket league

**Comment by joshhting** [comment]
Option 2: Factorio

**Comment by joshhting** [comment]
Option 3: Mooch off of RJ social

**Comment by joshhting** [comment]
Option 4: Card games

**Comment by joshhting** [comment]
Option 5: Crash an IGVC meeting

**Comment by jgkamat** [comment]
Looks like we'll be playing factorio.

Right now, my best idea is to schedule this for a saturday, probably before software training (6PM). Anyone have any times that they prefer more?

**Comment by jgkamat** [comment]
This event will take place from 1-4PM in IC205. :tada:

**Comment by ashaw596** [comment]
lol. +D Today?

**Comment by jgkamat** [comment]
Whoops, I'm so bad at this, I updated the comment.

**Comment by joshhting** [comment]
Are we booking the room for this?

**Comment by jgkamat** [comment]
Yup, the room should be booked (IC205)

**Comment by joshhting** [comment]
@jgkamat So Jason & John can't make that time. Could you send out a whenisgood to determine the optimal weekend for this?

**Comment by jgkamat** [comment]
We've already booked the room, and I don't think it's a good idea to cancel/re-book the room .

From earlier:
>Right now, my best idea is to schedule this for a saturday, probably before software training (6PM). Anyone have any times that they prefer more?

I'm hoping that this can lead into an informal factorio server we can play on whenever.

FWIW, it's possible to 'attend' remotely, since we'll be just playing factorio.

I think it's a better idea to just do another one next semeser or another one in a couple weeks, re-scheduling will just add confusion IMO.

**Comment by jgkamat** [comment]
Because of scheduling mishaps, the location has been moved to **CoC 102** instead of the IC. I'm updating the previous post as well, so people don't get confused. Perhaps we should send an email to the robocup mailing list too :P.

**Comment by joshhting** [comment]
@jgkamat would you like to do the honors
