### ISSUE TITLE
Remove unused else block in defense.py

### ISSUE THREAD

**Issue by joshhting** [RoboJackets/robocup-software#1007]
We can delete the `smart` variable and the corresponding else block after it, because we only use the block under `if not smart:`.

**Comment by jgkamat** [comment]
Relevant code is [located here](https://github.com/RoboJackets/robocup-software/blob/b87bb0e48fbaaaee0ea4878e03dfd62ab6f098c4/soccer/gameplay/tactics/defense.py#L454-L469)
