### ISSUE TITLE
Clear 'unselected' plays during a playbook load

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#1014]
When loading a playbook, new plays are added, but checked plays are not deleted. This caused a small problem at comp, and I really don't want to have to deal with that again.

Bonus: Add a indicator on the plays panel showing if the playbook was modified manually (in the program) or if it's freshly loaded from the file.

**Comment by krispreza** [comment]
In your above comment you say that checked plays are not deleted. I am assuming that you don't actually want to delete the plays from the play registry but just want to uncheck/disable them right?

**Comment by jgkamat** [comment]
yup, I just want them restored to 'unchecked'. Deleting them would probably be overkill.

Sorry for the confusion :)
