### ISSUE TITLE
Create a list of the all the different subbehaviors

### ISSUE THREAD

**Issue by JNeiger** [RoboJackets/robocup-software#1039]
Maybe put this in a doc page somewhere or something

**Comment by chachmu** [comment]
Is this not in doxygen?

**Comment by JNeiger** [comment]
I'm not seeing one, but I could be wrong

**Comment by chachmu** [comment]
It would appear that I am wrong, there is a list of *everything* but that isn't very helpful since it is sorted alphabetically instead of by type or even if it comes from c++ or python.
