### ISSUE TITLE
Fix error message in test_field.py 

### ISSUE THREAD

**Issue by Jason27chan** [RoboJackets/robocup-software#1040]
make this line
msg = "evaluation.field.space_coeff_at_pos not functioning as intended: "

into this line
msg = "evaluation.field.field_pos_coeff_at_pos not functioning as intended: "

**Comment by WilliamHZheng** [comment]
test_field.py does not seem to exist. I can't find this file anywhere in this repository.

**Comment by fgodoy3** [comment]
I second that. File does not exist

**Comment by JNeiger** [comment]
This is still in another pr. It'll be merged in eventually

**Comment by JNeiger** [comment]
Scratch that, it looks like it was just merged in

**Comment by ajhammond12345** [comment]
Found the file in soccer/gameplay/tests but that msg does not exist to be changed.
