### ISSUE TITLE
Different PID settings for different types of motion

### ISSUE THREAD

**Issue by JNeiger** [RoboJackets/robocup-software#1047]
We should add some sort of setup where you can specify different PID values for different plays. This can allow us to optimize the PID response for different actions.

For example, the goalie should have a much faster "rise time" when trying to intercept the ball while the pass receiver should be a little more accurate when collecting the ball.

**Comment by chachmu** [comment]
Should we add that as a pid setting or should we have that be part of the acceleration/velocity profile that we pass the path planner?
