### ISSUE TITLE
Change pathplanning to prefer movement in the forward / backward direction

### ISSUE THREAD

**Issue by JNeiger** [RoboJackets/robocup-software#1048]
The 2015 robots are not very consistent when moving in the left and right. We should try and make the robots prefer moving forward or backwards when moving to their target location. This should improve consistency when moving around the field.

**Comment by Jason27chan** [comment]
@JNeiger Is this still something you want? We're changing the motion control for montreal, right?

**Comment by JNeiger** [comment]
I think we are good for now. We'll find out soon enough though.
