### ISSUE TITLE
forward_packet

### ISSUE THREAD

**Issue by maxaubel** [RoboJackets/robocup-software#1054]
Hey guys!

![forward_packet](https://user-images.githubusercontent.com/28493557/32692957-92b05034-c700-11e7-96ca-61546cfefa1d.png)

So now we have this issue: 
We connected successfully connected our own RF communicator using the simulator. We're sending the "forward_packet" you built, but we could not be able to understand where that packet is built.

**Comment by JNeiger** [comment]
Hi @maxaubel 
[This ](https://github.com/RoboJackets/robocup-common/blob/a107d2e7041b9aa493b83acd8b356779426a99b1/firmware-common/common2015/utils/rtp.hpp)is the file that contains the rtp packet declaration. I don't mess with the radio too much, but I believe this is what you are looking for.
