### ISSUE TITLE
Remove excessive printing when running plays

### ISSUE THREAD

**Issue by joshhting** [RoboJackets/robocup-software#1067]
There are two print statements in https://github.com/RoboJackets/robocup-software/blob/master/soccer/gameplay/evaluation/path.py#L111 and https://github.com/RoboJackets/robocup-software/blob/master/soccer/gameplay/evaluation/path.py#L112 that clog up the console when running adaptive formation. They should be either deleted or wrapped up into an `if debug:` statement and have `debug` be set to `False` by default. This would result in a much cleaner looking console.

**Comment by kylestach** [comment]
This particular instance was fixed by #1071.
