### ISSUE TITLE
Team 2 Play

### ISSUE THREAD

**Issue by joshhting** [RoboJackets/robocup-software#1077]

**Comment by joshhting** [comment]
Yo I added @liquidmetal9015 to your guys' team so there are now 6 people on both teams

**Comment by liquidmetal9015** [comment]
I created a branch called team2play on the robocup repo. I'm the only one here today so idk. Here is a groupMe Link: https://app.groupme.com/join_group/36632121/jLdHEN so that we can communicate. You can also give me your groupme info and I'll add you.

**Comment by chachmu** [comment]
This plan appears to have died :(
