### ISSUE TITLE
Processing Hung

### ISSUE THREAD

**Issue by maxaubel** [RoboJackets/robocup-software#1084]
What would be a reason for the "Processing Hung" to happen?
It started appearing after some modifications related to the transmission.

![image](https://user-images.githubusercontent.com/28493557/33799785-63e1284c-dd11-11e7-809c-738412e0f946.png)

**Comment by jgkamat** [comment]
Hmm, I usually see the 'processing hung' error when for some reason, the processing loop (with the actual gameplay ai) is too slow to keep up.

This is set here: https://github.com/RoboJackets/robocup-software/blob/master/soccer/MainWindow.cpp#L866

I would think that either the changes you added are a bit too slow, or they are in a deadlock for some reason. If you want to give it some more time, you could try bumping up the threshold (right now, we display the message after 0.1 of hanging).
