### ISSUE TITLE
Port WindowEvaluator to C++ and add a python wrapper

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#112]
This seems to be the slowest part of our python code.  Let's see how big of a speed boost we can get by writing this in C++.

**Comment by justbuchanan** [comment]
@barulicm, when you get around to this, a nice thing to add that @jgkamat and I had talked about would be to have the WindowEvaluator return the estimated chance of making the shot (from 0-1).  Right now all the code for that is in evaluation/shot.py, but it duplicates a lot of functionality in WindowEvaluator and might as well be integrated in (possibly with some Config values for how we weight different parameters)

**Comment by barulicm** [comment]
@justbuchanan Initial testing shows an average 3ms shaved off per call to eval_pt_to_seg. This first pass was a pretty direct port. I should be able to improve performance further with a more deliberate wielding of the language.

**Comment by justbuchanan** [comment]
Sounds great!  One thought I had is that some of the use cases for this involve evaluating the same shot from many different points to choose the best place to choose from.  Do you think this is something that could go well with OpenMP?

**Comment by barulicm** [comment]
@justbuchanan I added a shot_success field to all windows. Any call to WindowEvaluator will populate this field for the windows returned.

On another note, OpenMP might help here. I've also been considering implementing a cache for evaluation results. This way, multiple calls to evaluate the same target & origin during a single frame will result in only one actual calculation.

**Comment by justbuchanan** [comment]
Sweet!  One thing that might be nice is if you want to change the distance and angle weights for shot eval to config variables, so we can tune them a bit easier.  I pulled the 0.7 and 0.3 out of my ass last year.

The cache would be cool, but I doubt we'd really ever get any hits.  Can you think of any scenarios where we'd run the same window eval twice in the same frame?

**Comment by barulicm** [comment]
I don't have any specific examples in our current code yet, but I imagine that we frequently evaluate shots between the ball and either of the goals, or between a robot's position and one of the goals. These feel like significant landmarks that many behaviors might be asking about.

**Comment by justbuchanan** [comment]
That's true.  I could definitely see us doing multiple of the same window eval in a frame at some point, although I don't think we have anything that does that right now.

**Comment by justbuchanan** [comment]
Done by @barulicm.
