### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by maxaubel** [RoboJackets/robocup-software#1125]
We are currently experiencing some troubles when trying to compile the most recent version.
This is what I try to "make"

![image](https://user-images.githubusercontent.com/28493557/39401367-be5f7776-4b19-11e8-9a07-bac1f9c34049.png)

**Comment by maxaubel** [comment]
This happened after trying to update the geometries of the new field (square penalty area)

**Comment by chachmu** [comment]
That can happen when you try to change things in the submodules. Try running:
 ```
make clean
git submodule update --init --recursive
```
If that doesn't work try rm'ing the directory and `git reset --hard`

**Comment by maxaubel** [comment]
Yes it worked, thanks!

**Comment by jgkamat** [comment]
Nice, ill close this, feel free to reopen if you run into more issues :)
