### ISSUE TITLE
Kickoff makes our decision tree disappear

### ISSUE THREAD

**Issue by Jason27chan** [RoboJackets/robocup-software#1136]

**Comment by jgkamat** [comment]
Im a bit confused by this, do you mean the behavior tree? I tested a full game a couple of weeks ago and everything worked fine. Could you take some screenshots? Are you sure all the relevant plays are enabled? 

If there is an issue, the earliest ill be able to fix it is Friday.

On June 5, 2018 8:39:59 PM EDT, Jason Chan <notifications@github.com> wrote:
>Assigned #1136 to @jgkamat.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ashaw596** [comment]
Idk. But with real robots. The kickoff play completed before the kick.
Maybe it was a vision issue tho or something.

**Comment by Jason27chan** [comment]
We can't reproduce this either. We'll worry about this when it comes up
