### ISSUE TITLE
Jiggling on the defense line

### ISSUE THREAD

**Issue by Jason27chan** [RoboJackets/robocup-software#1138]
Robots on defense are jiggling because they're not allowed in the goal zone. Should be easy to offset robots by a small distance

**Comment by jgkamat** [comment]
I think that the fix for #1098 was not fully tested. I think that if we bump
the range a bit more this should go away, but the problem could be deeper.

Jason Chan writes:

**Comment by Jason27chan** [comment]
we're finding a problem where robots are path-planning through each other.

**Comment by joshhting** [comment]
Apologies for not looking at this sooner, I'll tackle it this afternoon

**Comment by Jason27chan** [comment]
Is this still a problem @chachmu?

**Comment by chachmu** [comment]
@Jason27chan Probably, I haven't seen it quite as much since we improved motion control and better calibrated vision but we haven't really run the robots enough to say it is gone for sure.
