### ISSUE TITLE
Remove automatic 0 chance when shooting from beyond half court.

### ISSUE THREAD

**Issue by jcarn** [RoboJackets/robocup-software#1164]
The "eval_shot" method in evaluation.shooting returns a 0 when we are shooting from beyond the half-court line. Not shooting this far is a decision that should probably be made on the play level (which, for adaptive formation there is already a check for this). @JNeiger thoughts?

**Comment by JNeiger** [comment]
Yep, I read the rules wrong and thought you weren't allow to shoot past midfield.
