### ISSUE TITLE
Have soccer log current Commit

### ISSUE THREAD

**Issue by CollinAvidano** [RoboJackets/robocup-software#1169]
Have soccer log the id for the current commit on git. This would be incredibly useful during comp to review the code running during bad plays especially when we are running around changing stuff.

**Comment by jgkamat** [comment]
This is a great idea, this is already put in the title of soccer so adding it
to the log file should be pretty easy. We could just add it to the tree and it
should probably show up in the log viewer as well.

Collin Avidano writes:

**Comment by jgkamat** [comment]
Actually, this is already done:

>             Packet::LogConfig* logConfig =
>                 _state.logFrame->mutable_log_config();
>             logConfig->set_generator("soccer");
>             logConfig->set_git_version_hash(git_version_hash);
>             logConfig->set_git_version_dirty(git_version_dirty);
>             logConfig->set_simulation(_simulation);


Jay Kamat writes:
