### ISSUE TITLE
Use accelerometer and gyroscope on robot to help in motion control

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#118]
Should wait for new robot? How much does the new design change the firmware if any?

**Comment by jjones646** [comment]
These people use the MPU-6050 (same accel/gryo as MPU-9250). It has some pretty awesome control algorithms that is uses.
https://github.com/bitcraze/crazyflie-firmware

**Comment by justbuchanan** [comment]
@thaeds, Jon got a few breakout boards for the MPU-6050, which is the MPU that we've mostly decided on for the final control board.  Remind me at the next meeting and I'll get you one.  It should be mostly the same as interfacing with the one you currently have.

**Comment by thaeds** [comment]
Cool, will do. Chris and I are meeting up after the general meeting today,
if you want to join!

**Comment by ashaw596** [comment]
Just wondering, how well is the mpu chip working anyways?

**Comment by justbuchanan** [comment]
@thaeds, I remember you looking at this back at the beginning of this past semester.  What were you able to get it to do back then?  I'm going to look at getting this up and running with our motion control, anything I should know that you can remember?  Thanks!

**Comment by justbuchanan** [comment]
Found some good info on filtering IMU output - saving here for future reference.

http://avikde.me/IMU-Filtering-STM32-MPU6000/

**Comment by thaeds** [comment]
I had accelerometer data printing out using this source
http://pastebin.com/bm4xAZPm and this library
https://developer.mbed.org/users/aberk/code/ADXL345/
Hope it helps!!

**Comment by justbuchanan** [comment]
Cool, thanks!  I'll look into that sometime this week and what I can figure out.

**Comment by justbuchanan** [comment]
@jjones646, what's the status on interfacing with this via firmware?

**Comment by jjones646** [comment]
It's works when running on a control board and all the I2C stuff is integrated into the RTOS stuff - so it's all non-blocking. I think hard fault that comes up with an mbed that's no connected to anything results from some self-test code that I added a while back. I know it's worked fine on one of the earlier commits.

**Comment by jgkamat** [comment]
Issue moved to rj/rc-firmware
