### ISSUE TITLE
Fix comments in miscellaneous files

### ISSUE THREAD

**Issue by Jason27chan** [RoboJackets/robocup-software#1188]
* Delete comment in defensive_positioning.py Line 23-24
* Delete comment in basic_122.py Line 65-67
* Delete comment in RRTPlanner.cpp Line 303, 312
* Fix shoSot to shoot in forward_pass.py Line 35

**Comment by bopas2** [comment]
me

**Comment by TahaKrarti** [comment]
nope me

**Comment by bopas2** [comment]
wrong

**Comment by JNeiger** [comment]
Everything but the RRTPlanner stuff is done. Imma close this
