### ISSUE TITLE
Make a script for mechanical to easily run robots

### ISSUE THREAD

**Issue by Jason27chan** [RoboJackets/robocup-software#1189]
Often, mechanical wants to run robots, but the entire process of starting up robots and vision can be a hassle. This would also be helpful for new members

This should encompass everything one would need to run soccer on a field including
* Opening vision
* Pulling 
* `make run`

Please add to this list as appropriate

**Comment by chachmu** [comment]
This is already done and on the desktop of the computer farthest to the left by the field.

**Comment by joshhting** [comment]
Is that script in the repo? I feel like it should be, so that mechanical can, e.x., use it to test bots during comp with someone's laptop

**Comment by chachmu** [comment]
@joshhting They shouldn't use the script at comp because launching vision on your own computer will interfere with the field vision. This is pretty much only useful at our vision computer. I don't think it is too much to ask them to learn how to run `make run` at competition

**Comment by jgkamat** [comment]
It's probably a good idea to check it in anyways in case the computer
has a hard drive crash or you guys want to look at the change history of the
file. You could use a symlink to keep an icon on the desktop while still
having it live under source control.

Matthew Woodward writes:
