### ISSUE TITLE
QTime::fromMSecsSinceStartOfDay will break at midnight

### ISSUE THREAD

**Issue by Jason27chan** [RoboJackets/robocup-software#1191]
At comp, we changed  QTime().addMSecs(elapsedMillis) to QTime elapsedTime = QTime::fromMSecsSinceStartOfDay(elapsedMillis). @ashaw596 pointed out that this will break at midnight.

This functions is used in Logviewer.cpp Line 137 and MainWindow.cpp Line 484

**Comment by jgkamat** [comment]
How will this break at midnight? I think this would break after `elapsedMillis` is larger than 1 day (because a QTime represents clock time). We probably shouldn't be using QTime for this anyway, since it's a duration.

**Comment by ashaw596** [comment]
Ohhh. That's what it's doing. Yeah Jay's right. My bad.

**Comment by JNeiger** [comment]
I'm going to close this since it doesn't sound like an issue really.
