### ISSUE TITLE
Remove comments in basic_122

### ISSUE THREAD

**Issue by JNeiger** [RoboJackets/robocup-software#1198]
Delete lines 65, 66, and 67 in `basic_122.py`. The comment function was moved to another file in C++.

**Comment by Alan-Penkar** [comment]
Mine!

**Comment by Alan-Penkar** [comment]
@JNeiger - lines 65, 66, and 67 in soccer/gameplay/plays/offense/basic_122.py aren't comments, only line 66.  That line does seem to comment on what follows.
