### ISSUE TITLE
Improve simulator

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#120]
As discussed in #105, there are a few improvements that need to be made to our simulator for it to be more effective.

Here's our current todo list for what needs to be done:
- [x] Remove the robocup-simulator-old repo since we'll be keeping the current simulator in this project
- [x] Improve the physics of the ball against the ground - right now the ball rolls significantly further in real life than in the simulator.
- [ ] Add a dribbler to robots the simulator?

**Comment by ra4king** [comment]
#182
