### ISSUE TITLE
Refactor magic constants in our_goal_kick and our_kickoff

### ISSUE THREAD

**Issue by JNeiger** [RoboJackets/robocup-software#1201]
It's nice to have all the magic numbers near the top as config values. It makes editing and adding new things easier.

In `our_goal_kick.py`
Add
```
MaxApproachSpeed = 0.5
MaxApproachAccel = 0.5
```
near line 22 with the other config values.

At lines 34 and 35, make it
```
kicker.max_speed = MaxApproachSpeed
kicker.max_accel = MaxApproachAccel
```

In `our_kickoff.py`
Add
```
MaxApproachSpeed = 0.5
MaxApproachAccel = 0.5
```
near line 16

At lines 83 and 84, make it
```
kicker.max_speed = MaxApproachSpeed
kicker.max_accel = MaxApproachAccel
```

**Comment by MomenYacoub** [comment]
Mine
