### ISSUE TITLE
Wing Defender

### ISSUE THREAD

**Issue by Alan-Penkar** [RoboJackets/robocup-software#1235]
Based on what was discussed today with @JNeiger, @Jason27chan, and @bopas2 - this is the spec I came up with for the wing defender skill.  Please feel free to comment or add anything I missed.

Wing Defender - 
    This skill should serve as a marking technique to defend against threats without the ball, but in good position to shoot if they receive the ball.  The functional goal of the wing defender skill is to be in position to potentially cut off the pass YET be in good position to defend against mark_robot's shot if it does receive the ball.
    The positioning of the defender will be between ballside and goalside marking as specified in polar coords from the mark_robot. Note: We are not explicitly setting theta, instead we will set the proportion of the angle to go from ballside to goalside mark lines , with goalside_ratio =0 being ballside marking and goalside_ratio=1 being goalside marking.

Functionality still being specified:
-The exact setting of goalside_ratio and mark_distance based on mark_robot's position and velocity.
 --Probably going to be a fairly iterative definition.

Possible enhancements:
-Account for lag in the detection of a pass/kick: both in transitioning to intercept and setting the polar coordinates. 

1 state for execute wing defending
Maybe a 2nd state to determine when to switch to intercepting

'''
@param mark_point: default to None, overrides the mark_robot if set to not None
@param mark_robot: Robot to defend against
@param goalside_ratio: Percentage of the angle from (mark_robot,ball) to (mark_robot, KickEval:shot_pt) to line up on.  This functions as a sort of mixing between ballside and goalside marking.
    (goalside_ratio of 1 indicates a goalside_mark, 0 indicates a mark skill)
    This will be set in this skill by a formula that isn't well defined yet, and will likely be very fluid in testing.
@param mark_distance: Distance from the mark point/robot to the defender.
    This will be set in this skill by a formula that isn't well defined yet, and will likely be very fluid in testing.
'''

**Comment by kylestach** [comment]
Closed with #1270.
