### ISSUE TITLE
Wall tactic - potential second state

### ISSUE THREAD

**Issue by bopas2** [RoboJackets/robocup-software#1247]
We should consider adding a second state to the wall tactic where the wall maintains formation as the ball is shot towards our goal. Currently, if the ball is shot, and we the have mark point set to the ball itself, the wall will follow the ball as it moves towards the goal. One solution to this is to not build the wall against the ball, but rather against the robot shooting the ball. This can also cause problems if the kicking robot begins to move after shooting the ball -- as the wall may move out of the defense line. We should add a second state that detects when the ball is shot and to maintain the wall's formation until the ball has been blocked.

We're mainly waiting for Joe's vision filter method that will detect when the ball is kicked so we may be able to use that to detect when to hold the formation still. Perhaps this detection should be used in the higher defense tactic. Need to investigate.

**Comment by JNeiger** [comment]
What information would you like from the module? I believe I have kick velocity, kicking robot, and kick location (as well as time)

Also, what kinda of API would work best for you guys? It's basically a single variable in C++ that's the best kick estimate as the current time. It may change throughout the life time of the kick as it better estimates the kick itself. Do you want there to be a single flag each iteration saying there was a new kick and the information about it? Etc
