### ISSUE TITLE
Clear play

### ISSUE THREAD

**Issue by HussainGynai** [RoboJackets/robocup-software#1320]
## Description

A play that will activate on defense that will try to chip the ball up field while also moving robots up field

## Requirements

 - Chip the ball up field
 - Move robots up field

## Design

https://docs.google.com/document/d/1l8Yg3pnwk4c_xT5Ben8W-NOcU-Ope5kT-iGmuAXvBcY/edit# (link)

**Comment by kylestach** [comment]
Scoping this for the next testing milestone based on your time estimate.
