### ISSUE TITLE
Joystick Refactor

### ISSUE THREAD

**Issue by CollinAvidano** [RoboJackets/robocup-software#1325]
## Description
Processor is a mess and really should not contain all the joystick code directly. I want to move the majority of joystick code out of processor and into a separate class (will probably be named manualmanager) that would hold all joystick and other manual input related state and functionality.

## Requirements
- No joystick-specific code in Processor
- All joystick logic is kept locally in something that is not Processor; that thing should be responsible for modifying packet commands
- Should support an unlimited number of joysticks being plugged in
- Should support any number of robots being manually controlled
- Should support extension via keyboards and other input methods

## Design
https://docs.google.com/document/d/1V0zQN19UZK7d2m-9Otd1NLVLHHrPHqdAuiDt_6dU6iw/edit?usp=sharing

**Comment by kylestach** [comment]
Closed by #1461
