### ISSUE TITLE
Add automated testing framework

### ISSUE THREAD

**Issue by kylestach** [RoboJackets/robocup-software#1328]
## Description
A system to automatically run tests for plays. The GUI will allow users to select sets of tests to run. The system will then automatically place robots and the ball in the locations specified by the tests, run the tests, and report the results.

## Requirements

 - A user should be able to specify a list of robot positions and velocities, ball position and velocity, and game state. 
 - Soccer can be launched in “testing mode” via a command-line argument specifying a python script that specifies above data. 
 - Soccer will then proceed through all testing scripts, running each situation until time limit. 

## Design

[Link to design document](https://docs.google.com/document/d/1jem3jhoX-xXPAJe7aBImg3YXuQ82eKvUvw6GmLgNdgg/edit?usp=drivesdk)

**Comment by kylestach** [comment]
@chachmu Is this done?

**Comment by liquidmetal9015** [comment]
I think this just needs the time limit and the command line launching. Of course we don't really have the "report the results" part as a part of the current system. The current system just sets up the game state and I think there might be some small issues of things that need to be set. Running it in sim2play mode may also not work great. Other than that we need to actually create testing scenarios.
