### ISSUE TITLE
Coordinated Pass Failure to Terminate

### ISSUE THREAD

**Issue by liquidmetal9015** [RoboJackets/robocup-software#1340]
## Description
When playing in simulated and real matches, we often end up in a state in which Coordinated pass should have terminated but it has not. 

1. Passing robot has fully lost the ball at any point before the pass was made
2. Passing robot fails to kick the ball, but is unable to get the ball again due to role requirements
3. The ball was intercepted in between the passing robot and the receiving robot.

All of these situations lead to major paralysis of the team.

![FrozenByCoordinatedPass](https://user-images.githubusercontent.com/8135314/65836576-63a68880-e2bf-11e9-8b29-d3fbf627d53e.png)

![CoordinatedPassNotInterrupting](https://user-images.githubusercontent.com/8135314/65836602-791bb280-e2bf-11e9-9d1a-2d95f9edd028.png)

## Steps to reproduce
1. Create one of the situations in which Coordinated pass should be failing. It will happen naturally when running sim2play

Result: Coordinated pass continues to run when neither the passer or the receiver are in a position to possess the ball.

- [x] This bug has been reproduced by someone else

## Additional information

The primary solution to this problem will probably consist of adding robust termination conditions to the various states of coordinated pass. Adding a conditions that look at the rate of approach of the ball to the receiving robot and at the possession of the ball might be good places to start.

**Comment by liquidmetal9015** [comment]
There is actually another major aspect to this: When the passing path becomes invalid due to obstacles getting in the way, coordinated pass tries to pass through them. This behavior needs to be fixed as well, probably by terminating coordinated pass. It's possible that coordinated pass needs some kind of overhaul.

Here is a demonstration of that behavior: 
![NotAValidPass](https://user-images.githubusercontent.com/8135314/65837646-fcd99d00-e2c7-11e9-9c8a-9d796eab3c1f.png)

Another instance:
![PanicKick](https://user-images.githubusercontent.com/8135314/65837669-49bd7380-e2c8-11e9-881e-f2af4bdaff27.png)

**Comment by liquidmetal9015** [comment]
To some degree Situational Analysis based play preemption should help with this, as the play that is calling the Coordinated Pass would be terminated once we enter the pileup state. But the general notion is that we should attempt to fix it in the current system, and that Coordinated pass failing should be an expected possible outcome when any of these things happen.

**Comment by kylestach** [comment]
Let's get some quality testing of this now that #1355 is merged, and then if we don't see the bad behavior we'll call it good to go.
