### ISSUE TITLE
There are no plays for the "Attack Goal" situation

### ISSUE THREAD

**Issue by liquidmetal9015** [RoboJackets/robocup-software#1343]
# Description

Normally you would design a play of whatever situation in a design document, then create an issue for you or someone else to make it. But since we are currently lacking any plays at all for "Attack Goal" situation, we are creating an issue to create a play for that situation at all. In the longer run we want to have at least a couple of plays for each situation, but for this issue just create a play for "Attack Goal" using whatever methodology just so we have a baseline for that situation.

Eventually this play will need to interface with the situation analysis module for score determination, but that functionality is still in development so for right now the play will be developed as a general play and that integration will be added in later on. The integration should be pretty seamless with only the score function being affected, and even then a regular score function will still be the default if we decide to disable situation analysis for any reason.

In the new situational plays paradigm, plays will only be active during a specific subset of game play. So you will only need to handle what happens inside that situation and should assume that your play will be artificially terminated when game play leaves that situation. (You may still want to have your play terminate itself on certain triggers however). Below I will describe the situation that this play needs to cover. 

# The Attack Goal Situation:

This situation is when we possess the ball (the ball is solely in the mouth of our robot) and we are in shooting range, which for now will be if we are on our opponents side of the field. The idea is to move the ball into a position where we can get a good shot off.

# Existing code and ideas:

To some degree we already have code that covers this situation in adaptive formation and basic_122. Looking at those plays should probably be the starting point and the splitting of adaptive formation into its offensive and defensive components is something that we are interested in regardless of if that results in a solution to this issue.

# Notes about design:

Currently plays have to control all the robots on the field, this will not always be the case. It is likely that we will expand our library of "latent behaviors" to help deal with this as needed where latent behaviors are tactics and skills designed to handle robots that are not a part of the primary maneuver the play is executing. For right now leaving robots idle is an option although we will need to assign them latent behaviors for better performance, there are a couple projects working on remedying this. Working around the default defense and goalie will also be necessary for the time being. We may decide to change how those work in the future.

Also keep in mind that writing additional tactics and skills is ideal when designing new behavior, as it will allow us to reuse those behaviors in other places.

# Requirements

- Have a reasonably performant play that fulfills the "Attack Goal" situation

# Design
[Insert link to design document here once you have created it](link)

**Comment by Jason27chan** [comment]
Basic 122 and adaptive formation can act as attack goal plays.
