### ISSUE TITLE
Make wall prioritize capture

### ISSUE THREAD

**Issue by Jason27chan** [RoboJackets/robocup-software#1389]
## Description
The wall play prioritizes forming the wall over capturing the ball. When we transition into the winger wall play, we want to prioritize contesting the ball over forming the wall.

Edit** In the defend goal situation, our robots will use a winger wall defense. In the wall defense the forms around the ball, the situation usually ends up turning into a clear or a scramble, so this is not a high priority issue as of right now

## Steps to reproduce
1. Replicate a defend goal situation. Have the ball be on our side of the field in the possession of an enemy robot

Result: Our robots should form a wall around the ball with winger defenses for possible opponent passes. Our robots may or may not stand in front of the ball with no attempt to get it

**Comment by tjones320** [comment]
I think this is mostly right. Would we want to directly capture or do we want to clear and kick on break beam? Especially if we are wanting to play purely defense getting a shot off would be pretty dangerous.
