### ISSUE TITLE
There is a crash in the wall tactic

### ISSUE THREAD

**Issue by liquidmetal9015** [RoboJackets/robocup-software#1407]
## Description
There is an error in the wall tactic

## Steps to reproduce
1. Use wingerwall (only tested in sim2play, probably critical to triggering)

Result: 
![WallStackTrace](https://user-images.githubusercontent.com/8135314/73801888-df42a580-4789-11ea-89af-c1802bf32f1d.png)

**Comment by Jason27chan** [comment]
Solved in #1417
