### ISSUE TITLE
Rotate radio protocol velocities

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#142]
Our radio protocol cmd_x and cmd_y velocities are backwards from what would seem to make sense...

See here for info: https://github.com/RoboJackets/robocup-software/blob/master/doc/radio-protocol-2011.txt#L23

When we write the new firmware for the MBED-based control board, we'll have two sets of firmware that are completely separate, but need to speak the same radio protocol.  Now would be a good time to make sure our protocol makes more sense.

**Comment by ashaw596** [comment]
Is this moot with the new firmware and stuff? Or do we still want to d othis for backwards compatibility?

**Comment by justbuchanan** [comment]
Yeah we can close this.
