### ISSUE TITLE
Shrink unassigned -> assigned skill delay from 1 frame to 0

### ISSUE THREAD

**Issue by JNeiger** [RoboJackets/robocup-software#1464]
## Description

There is currently a single frame delay between creating a skill, and being able to run it. This is due to the design of the play system as a whole. Every frame, two main things happen, the state machines are run, then the robots are assigned to `single_robot_behaviors` in that order. For skills specifically, they cannot be run in the state machine run step unless they have a robot assigned. Combine these two together and you get this behavior.

Control flow is as follows
```
State machine run
   single_robot_behavior created but not run since it doesn't have robot
Role assignment
   single_robot_behavior assigned robot
--- New Frame ---
State machine run
   single_robot_behavior has robot so it's run now
```

[Here ](https://github.com/RoboJackets/robocup-software/blob/515467890d8ac7bb222bac84042c85c548d469a4/soccer/gameplay/composite_behavior.py#L99)is the check to see if we should run the `single_robot_behavior`. 

[Here ](https://github.com/RoboJackets/robocup-software/blob/staging/soccer/gameplay/root_play.py#L133)is the role assignement.

[Here ](https://github.com/RoboJackets/robocup-software/blob/515467890d8ac7bb222bac84042c85c548d469a4/soccer/gameplay/single_robot_behavior.py#L27)is where robots are actually assigned to `single_robot_behaviors`

## Requirements

 - Reduce the delay from 1 frame to 0

## Design

To fix this, some notion of "newly" assigned `single_robot_behaviors` will have to be created. And then the subbehavior tree will have to be walked down to figure out the instance in which has been newly assigned to run that one specifically.

Newly assigned may be a new `single_robot_behavior` has been added this frame, a old `single_robot_behavior` has finally been assigned, or a new robot has replaced an old robot in a `single_robot_behavior`.

To decide how to walk down the tree, there is a tree in `role_requirements` that may serve this purpose.

This will complicate the state machine code fairly significantly as well as the assignment process.

---
Another solution: 
Also, question: couldn't we separate out the "spin plays" step and the "spin skills" step? i.e.:
1. Run play; this can add or remove skills/tactics
2. Run role assignment
3. Spin skills/tactics

**Comment by kfu02** [comment]
outdated thanks to #1811
