### ISSUE TITLE
Change soccer interface layout

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#147]
A lot of the useful information in our soccer program is hidden in tabs along the side.  This is fine for development, but when we're in competition, we're not allowed to touch the computer.  It would be really helpful to have a competition mode or an improved general UI so we can see all of the important stuff right off the bat without having to search.

A few things that would be good to see:
- [x] The field view (obviously)
- [x] Robot statuses - if anything has a fault/error this would let us know what bots we need to swap out at the next opportunity.  See #8 
- [x] Game status / last info from the referee
- [x] The behavior tree
- [x] enabled plays?
- [ ] error/info log output

@barulicm anything I missed here?

**Comment by justbuchanan** [comment]
![img_0011](https://cloud.githubusercontent.com/assets/115131/5733352/b9caa6ca-9b6f-11e4-9209-978f28fc9231.JPG)

**Comment by justbuchanan** [comment]
@monamohebbi, how's progress coming along on this?  We've got the status panel about ready to merge, but I'm hesitant to do it before merging this one b/c it'll cause some difficult-to-resolve merge conflicts with the UI files you've been working on.

**Comment by monamohebbi** [comment]
Almost done! I just have to take out some of the extra tabs I can probably
finish it over spring break. Also do you guys have any preferences to how
the images expand?

**Comment by justbuchanan** [comment]
Sounds great!  Which images were you thinking about?

**Comment by monamohebbi** [comment]
For some reason the field and tab widgets won't expand with the rest of the screen even after I set their properties to expanding. I'll keep searching for a solution, but I just wanted to know how important it would be for them to do this

----- Reply message -----

**Comment by justbuchanan** [comment]
If you want to push it to a branch on your GitHub repo, I can download it and take a look at it over the break.  I'm not sure off the top of my head though what the issue would be.  Setting it to expanding sounds right to me.
