### ISSUE TITLE
[TODO] Replace straight-line RRT

### ISSUE THREAD

**Issue by kylestach** [RoboJackets/robocup-software#1511]
Currently our planners act in two steps:
1. Try a straight-line path to the goal
2. If that doesn't work, do an RRT

Step 1 is currently implemented by running several iterations of an RRT with a goal bias of 1.0. This can be greatly simplified by just checking if a straight line, from the current position to the goal, will hit any obstacles.

Pull request: #1496 

Link to TODO, or file number/line: RRTUtil.cpp:91

**Comment by kfu02** [comment]
@kylestach handled this in #1496, this issue was just never closed

https://github.com/RoboJackets/robocup-software/pull/1496/files#diff-fa11166229275cdca85a81c0c12d22770cee2b7cff1f83c1686a05c05d2abe95R39-R41
