### ISSUE TITLE
Develop new radio protocol for high-performance and reliable transfer

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#155]
We're looking to change our radio protocol for the new control board.

A few objectives:
* MBED-based (for both the base-station and on the robot)
* wireless serial port so we can open a shell onto the board without being plugged in
* Suppport for more than six robots (right now we only use six, but in the near future, we'll need to support more)

Right now we're considering having two radio channels that run simultaneously using two separate hardware radios per robot and base station.  One channel would be for motion commands coming to the robot and the other would be a session-oriented reliable channel that would be for firmware updates, robot status info, and serial comm for a terminal session.

A few things to investigate:
* 900MHz (cc1101 chip) vs 2.4GHz (NRF chip)
* Can we do everthing we want using a single 2.4GHz radio?
* How do we implement the session-oriented reliable portion of the protocol?  What MBED libraries are available?

Relevant info:
* https://docs.google.com/document/d/1Ma9RRYa4p4PcaC-CYx8j00_UTisCI85ou5XQsW_cU_A/edit?usp=sharing
* http://wiki.robojackets.org/w/RoboCup_Radio_2009

cc @bstrong1218 @ryanstrat @ChrisDoho

**Comment by justbuchanan** [comment]
I think the latest plan for radios is to use the [cc1201 chip](http://www.ti.com/product/cc1201), which is an updated version of the cc1101 we're currently using.

**Comment by ashaw596** [comment]
The CC1201 looks pretty good. It's 900 Mhz and supports the 1.25 MHz. Just wondering though. Do we have any testing chips? And are there any libraries for it already?

**Comment by jjones646** [comment]
1.25 Mbps. It's a relatively new chip, so I doubt there's much out there yet. TI does provide [a few things](http://www.ti.com/product/CC1201/toolssoftware) regarding the series. I've requested a few samples, so we should have something to test soon. Here's the [user's guide](http://www.ti.com/lit/ug/swru346b/swru346b.pdf).

**Comment by jjones646** [comment]
We use a much higher bit rate, but this is still interesting.
https://www.youtube.com/watch?v=4lodsJ_sKlY

**Comment by justbuchanan** [comment]
Here's a LaTeX doc that @jjones646 put together that has the tentative packet layouts and such for the new radio protocol:

**Comment by blueintegral** [comment]
I was reading the TDP and thought of one more random thing. In the future, you may want to try some simple channel scanning to avoid interference. You can get the CC1201 in your base station to tell you the RSSI of whatever frequency/channel it's currently assigned to. So you start with a hard coded initial frequency on both the base station and the robot, then have the base station scan across each channel and see if it's noisy, pick the best one, and tell the robot to move to that channel. If you start seeing lots of packet loss, you can try to automatically reassign frequencies. This probably isn't really necessary, but it would be kind of cool and might be a fun project for someone.

**Comment by guyfleeman** [comment]
Here's the link to the protocol GDoc: https://docs.google.com/document/d/1DBqsr7rLi9q3k9sROOHhTtqAbzGzHuztFSsPMocAkcI/edit?usp=sharing

**Comment by guyfleeman** [comment]
Would a variable length forward packet cause significant timing issues? I'd like to get at least 8 bytes per tuning section on the forward packet for parameter updates. This makes a tuning section larger than a control section.

**Comment by justbuchanan** [comment]
Closing this since it's been replaced by these 3: #154 #304 #618
