### ISSUE TITLE
[TODO] Make SSL ball stuff a `RosConverter`

### ISSUE THREAD

**Issue by HussainGynai** [RoboJackets/robocup-software#1588]
Pull request: N/A

Link to TODO, or file number/line:
https://github.com/RoboJackets/robocup-software/blob/ros2/rj_utils/include/rj_utils/conversions.hpp

DetectionBallMsg - @joshkirsh720 
DetectionRobotMsg - @adithya-gv

**Comment by kylestach** [comment]
Here is an example of a `RosConverter`:
https://github.com/RoboJackets/robocup-software/blob/1aa4cee694700dd91c4fbb1eb343c8dc772a50fe/rj_geometry/include/rj_geometry/geometry_conversions.hpp#L24-L42

You will need to make a new overload of `RosConverter` for the `SSL_DetectionBall` or `SSL_DetectionRobot` classes (associating them with `DetectionBallMsg` and `DetectionRobotMsg` respectively).

Make sure it goes in the `rj_convert` namespace, or it won't be found!

**Comment by kylestach** [comment]
Closed by #1597 and #1612.
