### ISSUE TITLE
Create routine for estimating camera latency

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#166]
It is possible with some fancy motion and math to calculate the delay between the camera taking a picture and our system receiving the coordinates of each robot.  If we know this delay more accurately, we can do a better job of using the camera data in our motion control system and predicting the state of the current field.  We can use the camera data + our prediction for what has happened during the delay.

Stanford described their method for doing this in their TDP, which can be found here:

http://robocupssl.cpe.ku.ac.th/_media/robocup2014:tdp:stanfordrc-2014.pdf

**Comment by justbuchanan** [comment]
@ashaw596 what's the latest on this?  Are we just waiting to test on real robots?  Also, what branch is this on?

**Comment by ashaw596** [comment]
Yeah. Basically just waiting for testing on real robots

**Comment by ashaw596** [comment]
It's on the albert/latency

**Comment by ashaw596** [comment]
@jpfeltracco @CollinAvidano 
Bump before I forget about this again. I had a mostly implemented play for helping calculate latency as well as something  implemented to account for it a bit.

**Comment by JNeiger** [comment]
@liquidmetal9015 This is implemented in your benchmark thing right?
