### ISSUE TITLE
Update log file format for random access

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#177]
Right now when viewing a log file, we have to load the whole thing into memory, which takes a pretty long time even for logs that aren't that long.  We can alter the file format so that random access is possible, so we can load frames as needed.

Ben Johnson, a RoboCup member from a few years back did this for the Stanford RoboCup team and gave me some info on the implementation.  Here's a lyx document describing the design: https://drive.google.com/file/d/0B6k6wyLporBec2hyaTRTSFZIYVNkLXltcWxOOXFqMllxSU9v/view?usp=sharing

**Comment by kylestach** [comment]
Closing as wontfix given that we're moving to bag files.
