### ISSUE TITLE
Add labels to StripChart

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#178]
We've got a pretty cool feature in `soccer` where you can right click an item in the `Tree` tab and show a graph of it over time.  The graph looks nice, but doesn't label the values or anything so it's hard to get useable data out of it other than just visually seeing the trend.  If we could have it label the x and y axes and show the value and slope when you hover, it would be a lot more useful.

**Comment by barulicm** [comment]
Closed by 93a23897d1ed18dc1f5d43134067c600cdaa5664 and 3d6407dfbc7ca3341eb6c8532060baf4c678450a
