### ISSUE TITLE
Use MBED to interface with ball sense hardware

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#186]
We need to pulse the emitter and read the detector to determine whether or not we have captured the ball.

**Comment by justbuchanan** [comment]
@gtrosawa what are the differences between the ball sensor setup this year and our previous one?

**Comment by justbuchanan** [comment]
@jjones646, @gtrosawa, We're looking at the ball sensor bar from last year and I'm not quite sure which side is which.  One "bulb" is red and one's clear - do you know which side is the detector?

**Comment by jjones646** [comment]
- Purple/Black = Detector
- Clear = Emitter

**Comment by justbuchanan** [comment]
@jjones646, @ryanstrat what's the status on ball sense boards?

**Comment by jjones646** [comment]
@justbuchanan These are ~1 month away I believe. The pcb design is finished - just a matter of getting the order in and then waiting at that point.

**Comment by ryanstrat** [comment]
​We ran into some issues panelizing the board that I think we've worked
through. They'll be ordered within the week with a 2.5 week turnaround.


Ryan Strat
ryan@str.at
(678) 517-3393
RoboJackets | RoboCup Project Manager
Georgia Institute of Technology

**Comment by JNeiger** [comment]
Is there a schematic for the connection between the Detector/Emitter and the mbed?

Right now I have the emitter connected to p20 and ground. The detector is connected to p19 and the same ground.

With this setup, whenever the emitter has power going through it, the detector values are shifted a significant amount (~500 units), almost as if there is some sort of cross talk between them.

**Comment by justbuchanan** [comment]
@jjones646, any ideas what might be causing the shift in values he's seeing here?  I looked at the breadboard setup for this yesterday and it all looked right to me.

@JNeiger, can you post a link to the branch that your code is on so I can check it out?

**Comment by JNeiger** [comment]
@justbuchanan https://github.com/JNeiger/robocup-software/tree/ball_sensor

**Comment by justbuchanan** [comment]
I browsed through your code and it all looks good to me.  Can you also post a pic of your breakout board?

**Comment by justbuchanan** [comment]
I think the solution may be to put a resistor in series with the photoresistor, as shown here: ![photoresistor circuit](http://teach.alimomeni.net/2012spring2/wp-content/uploads/2012/02/analogin_variableresistor.jpeg).

I forgot about having that resistor in there before, but that should fix the issue.  @jjones646, do you know what resistor the final board will have?
