### ISSUE TITLE
Interface with mechanical base ID chip

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#187]
This is how we will uniquely identify mechanical bases in order to do per-robot calibration.

**Comment by jjones646** [comment]
@justbuchanan We have some of these now.

**Comment by ra4king** [comment]
http://www.digikey.com/product-detail/en/DS2411R%2BT%26R/DS2411R%2BCT-ND/2045729

**Comment by justbuchanan** [comment]
This might be helpful: https://github.com/contiki-os/contiki/blob/master/dev/ds2411/ds2411.c.

It's not written for the MBED, but shouldn't be hard to port.

**Comment by ra4king** [comment]
That's the most cryptic code I've ever seen. I had to hunt down through multitudes of header files to dig for half of those variables/functions!

**Comment by ra4king** [comment]
Got it working.
https://github.com/ra4king/robocup-software/commit/63a8d9287d61e1212b25b6226b291d1c16fd8659

**Comment by justbuchanan** [comment]
Nice, that's awesome! :boom:.  The next step from there will be packaging it up into its own Ds2411 class.

**Comment by ra4king** [comment]
#281
