### ISSUE TITLE
Fix travis-ci build

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#190]
For some reason our travis-ci builds have been failing lately.  We install the `gcc-4.7` package through apt-get, then CMake says it isn't able to find it...  I'm guessing it's something to do with an Ubuntu package update, but not sure what.  Shouldn't take too much to fix, I just haven't had a chance to look at it.

**Comment by jgkamat** [comment]
This may have been an update in the cmake custom repository we are using. I'll look into that tomorrow.

**Comment by justbuchanan** [comment]
Not sure what happened, but it seems like it fixed itself...
