### ISSUE TITLE
robot2015 won't build unless latest version of gcc-arm-none-eabi

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#191]
Current solution:
Manually do this.
https://launchpad.net/~terry.guo/+archive/ubuntu/gcc-arm-embedded

**Comment by justbuchanan** [comment]
Do we just want to have ubuntu-setup add this repo?

cc @ashaw596, @jgkamat

**Comment by jgkamat** [comment]
maybe we could have it add it only if the user supplies a '--firmware' flag, or something along those lines.

**Comment by jgkamat** [comment]
If you know a better way of determining if this is running on a Ubuntu/Debian machine, let me know, but this seems to work fine so far
