### ISSUE TITLE
Add git version info to robot firmware

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#214]
In order to help with debugging, it's helpful to know what version of the firmware our robot is running.  To do this, we'll use the git SHA as a version id so that we can resolve the version on the robot to a specific commit in our codebase.

This would go well in either a `status` or `version` command in the robot's console/terminal.

Right now we have CMake setup to automatically generate a `git_version.cpp` file that has two variables: `git_version_hash` and `git_version_dirty`.  We'll need to compile this cpp file into the firmware binary and add a command to the terminal.

See the CMakeLists.txt file in the common/ folder for info on how `git_version.cpp` is generated.

**Comment by jgkamat** [comment]
I think I can take this one during the meeting today

**Comment by justbuchanan** [comment]
Sounds good!  I j ust assigned it to you.
