### ISSUE TITLE
Improve Defender and SubmissiveDefender tactics to clear ball

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#228]
Right now if a ball gets into the defense zone, the defenders just hover around it.  It would be much better if they had a "clear" state so they get the ball and kick it out of the way or pass it to another robot.
![screen shot 2015-02-21 at 8 51 31 pm](https://cloud.githubusercontent.com/assets/115131/6317023/cb993460-ba0b-11e4-86f2-79a039345d63.png)

**Comment by joshhting** [comment]
The defense zone is the area indicated by the green circle?

**Comment by justbuchanan** [comment]
The defense zone is the actually the white portion.  The green circle is sort of a lazy approximation to the goal zone that the defenders position themselves on.

**Comment by justbuchanan** [comment]
As of our changes during comp in China, defenders now clear the ball if it happens to land in their mouth.  However, if the ball is just a couple cm in front of them, they'll leave it there.  We still we want to be conservative about having a defender leave their post, but we should make the defenders clear the ball in more cases than they do currently.

**Comment by ashaw596** [comment]
Part of this and though a more high level, but I think not too difficult to
achieve I think we could write some simple heuristic that accounts for our
distance vs nearest oponent robot distance and trajectories to calculate a
probability of successful capture

**Comment by jcarn** [comment]
I'll look into this and see if I think I am up to the task

**Comment by jgkamat** [comment]
Look into the SubmissiveDefender Play, I think you'll only need to modify that file.

**Comment by jcarn** [comment]
When choosing to clear the ball or not, is the ratio between how quickly the defender can clear and how quickly the opponent can reach the ball a good metric?

**Comment by jgkamat** [comment]
That probably would be the best metric, but it would be hard to find out (we don't know how fast their robots are). Maybe distance would be an easy way to do this for now. 

Also, if the ball is moving, we want to intercept the ball where it is going to be, not where it is. Capture (should?) do this for you.

**Comment by jcarn** [comment]
I think it is important to take into account the case where they are moving at high speed towards the ball, so I'll look into a hybrid method since a case involving acceleration on their part would be hard to measure.

Gotcha, I will use that. Thanks
