### ISSUE TITLE
Remove any restrictions to chipping over the midline

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#249]
Chipping over the middle line of the field is allowed as per the new rules this year.

**Comment by barulicm** [comment]
These checks were never ported to the Python version of the Gameplay framework, so no action is needed.

**Comment by justbuchanan** [comment]
I think this stuff is still there because it's built into the `_chip()` method itself.

https://github.com/RoboJackets/robocup-software/blob/master/soccer/Robot.cpp#L364
