### ISSUE TITLE
Improve defense tactic

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#256]
I started several improvements to the `Defense` tactic at comp last year, but didn't get around to merging them.  They're still on the `defense` branch and just need a little work.

Enhancements include:
- ignoring previous shell id for role assignment of defenders
- allowing a variable number of defenders rather than always having 2
- reducing the number of windowing calculations required per iteration

A few other things to improve:
- [ ] Pass estimation doesn't really work
- [ ] Shot score is sometimes calculated incorrectly
- [ ] More optimal blocking of multiple threats

**Comment by JNeiger** [comment]
@Alan-Penkar This may be of interest to you. I think you already have more than 2 robots and improving blocking of multiple threats.

I want to say pass estimation / shot score has been improved since this was made.

**Comment by Alan-Penkar** [comment]
Thanks Joe, helpful to see the history- Defense.py should get broken out and rewritten by summer.  Since we're already discussing this and the issue is fairly vague, we can probably close this out though.
