### ISSUE TITLE
Show (x, y) location of cursor when hovering over the field

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#257]

**Comment by jedyang97** [comment]
Hi @audreyvnelson , I am Jed. Sorry for accidentally unassigned you from this issue. I don't know there can only be one assignee per issue. I am working on this problem in branch jed/hoverdisplay and  #501 now. Please let me know if you still want to work on it. I'm assigning you back. Again, sorry for that. :-p
