### ISSUE TITLE
Add buttons to soccer for loading and saving playbooks

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#274]
Simple UI dropdown menu buttons for loading and saving playbook files.

**Comment by ra4king** [comment]
Has this been completed?

**Comment by justbuchanan** [comment]
Yeah, didn't you do it? 4c94d7859a4173eb1854f9fc25537dbe6f497275

**Comment by ra4king** [comment]
Oh wow I'm forgetful, I don't remember creating the UI for it heh.
