### ISSUE TITLE
Put together a guide for contributing to the project

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#275]
This will go on the documentation website (through Doxygen) and outline best practices for working on new features / fixes and describe the process for getting those changes merged into the main project.

A few things to cover:
* topic branches for each separate issue
* purpose of the master branch
* standards a pull request should meet before being merged
* documentation and unit test best practices
* code formatting

**Comment by jgkamat** [comment]
Just for reference,
[this is a really good git introduction](https://docs.docker.com/project/set-up-git/), that shows the basic process of pull requests/forks, etc. It's not great for a total begginer to git though.
