### ISSUE TITLE
Nuke all tabs in favor of spaces

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#277]

**Comment by ashaw596** [comment]
RIP tabs.

**Comment by joshhting** [comment]
Aww

**Comment by jgkamat** [comment]
[This](http://nickgravgaard.com/elastic-tabstops/) is a pretty interesting concept regarding tabs. Unfortunately its not implemented yet

**Comment by ashaw596** [comment]
inform supports it? lol

**Comment by ashaw596** [comment]
There actually are some plugins for it.
https://github.com/SublimeText/ElasticTabstops

**Comment by jgkamat** [comment]
Its kind of weird that plugin isn't on the main page. Some people are thinking about writing a vim patch for it too...

**Comment by justbuchanan** [comment]
That is an interesting idea...  I actually like the way that works over regular tabs.  I'd rather not do anything though that requires everyone to have special editor plugins.

I'm closing this issue in favor of #161 since it encompasses spaces/tabs as well as all other formatting.
