### ISSUE TITLE
Improve evaluation of shots and passes

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#298]

**Comment by justbuchanan** [comment]
One thing that we could use here that we don't do currently is model the % chance of kicking where we aim as a gaussian as described [here](https://books.google.com/books?id=oO6YNGtlzbcC&pg=PA298&lpg=PA298&dq=robocup+shot+gaussian&source=bl&ots=9xo_iq6A8I&sig=WKDCuM5wph57wJdpNzo_l1Z3vPA&hl=en&sa=X&ei=A6o9VZvjDZLOgwTi3oCYBA&ved=0CB4Q6AEwAA#v=onepage&q=robocup%20shot%20gaussian&f=false).  That's an old link, but the math is pretty timeless.  The basic idea is that when we aim for a certain shot angle, the angle the ball actual leaves the robot at will follow a normal distribution centered at the aimed-at angle.  The key here is to figure out the std dev of this distribution, which is something that we'll have to measure.  Once we know that, we can do a normalcdf using the angular width of the segment available to shot at, which gives us the chance that we'll make the shot.

**Comment by ashaw596** [comment]
Once we figure out the variance and mean (I mean I hope it kicks straight
on avarage), boost seems to have a good implementation for this (assuming
it follows a normal distribution).
http://www.boost.org/doc/libs/1_42_0/libs/math/doc/sf_and_dist/html/math_toolkit/dist/dist_ref/dists/normal_dist.html
