### ISSUE TITLE
New Plays/Behavior Tree Panel dissapears when shrinking beyond a point

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#301]
As said, if you try to shrink the new right panel, it disappears.
![map17](https://cloud.githubusercontent.com/assets/4349709/7341346/70bde1a4-ec6e-11e4-8571-26f8f0241c38.png)

Also, when shrinking the window beyond a point, the field overlaps the right panel.
![map16](https://cloud.githubusercontent.com/assets/4349709/7341339/5544e634-ec6e-11e4-99af-f5c96906f14c.png)

Also, it would be nice if we could make the plays/behavior tree segments resizable, vertically. 

No major problems, but we should probably fix them before fall next year. I'll look into how qtcreator works over the summer

**Comment by justbuchanan** [comment]
Just pushed a commit to master that puts the plays and behavior tree views in a vertical splitter so they're resizable.  I also prevented collapsing of the tab widget.  I'm not having the same issue with overlap on my computer, so maybe you can show me that on your computer sometime.

**Comment by jgkamat** [comment]
Yah, this was only a problem on my messed up window manager, otherwise everything else is good now

**Comment by ashaw596** [comment]
=). Nice.
