### ISSUE TITLE
Integrate automatic ref into simulator

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#303]
There's an open source automatic referee that can send ssl-refbox commands automatically just by taking in ssl-vision data.  I'm not entirely sure of its current state / how well it works, so we'll need to do that before proceeding.  Integrating this with our simulator would allow us to simulate entire games and not just a little bit of back and forth.

https://code.google.com/p/ssl-autonomous-refbox/

**Comment by jgkamat** [comment]
Blocking #841
