### ISSUE TITLE
Infinite Loop Style

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/robocup-software#309]
Three options, pick one:
- while(true) { }
- while(1) { }
- for(;;) { }

We really should be consistent. I'm not intimately familiar with arm-specific compilers, but normal gcc compiles these down to the same instructions. I'm partial to while(true) as the clearest, but it doesn't matter as long as we don't switch every time we write a loop.

**Comment by ashaw596** [comment]
I think true is good. Or 1

**Comment by justbuchanan** [comment]
I agree.  I personally think the first is most readable, but as long as they're consistent.

**Comment by barulicm** [comment]
mbed has no 'true' / 'false' constants? I can use a smart pointer, but can't write "while (true)" what language is this? So disappointed :frowning:

**Comment by justbuchanan** [comment]
Are you in a .c or .cpp file?  I see bools all over the place in robot2015 and it builds fine on my computer.

**Comment by barulicm** [comment]
I think I actually had something wrong with my build setup. I was in main.cpp having problems, but they seem to have disappeared now. It may also have had something to do with a few unnecessary extern "C"s that I got rid of.
