### ISSUE TITLE
Pull field dimensions from vision packet

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/robocup-software#334]
SSL-Vision now includes field geometry in vision packets. We should at least add the option of pulling field constants from this data. This will help smooth over the pains of the inevitably erroneous fields at competition.

**Comment by justbuchanan** [comment]
Here are the protobuf files for ssl vision: https://github.com/RoboCup-SSL/ssl-vision/tree/master/src/shared/proto

And here's the part of our code where we read the vision packets: https://github.com/RoboJackets/robocup-software/blob/master/soccer/Processor.cpp#L298

Also take a look at #335

**Comment by jgkamat** [comment]
Are these packets implemented in our simulator? I tried out a basic setup and I'm getting 0 for width/height.
https://github.com/RoboJackets/robocup-software/commit/592739285db0eab2823f383b01eac7dcb3df5efd

**Comment by barulicm** [comment]
The simulator sends packets, but it might not fill out all of the fields. So they're atleast partially implemented.
