### ISSUE TITLE
Setup app packaging with CMake for easy distribution to non-developers

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#336]
We should do this for Ubuntu and OS X (if it's not too difficult).

**Comment by jgkamat** [comment]
If anyone is interested in learning CMake, this would be a good issue to tackle.

[these are the docs page](https://cmake.org/Wiki/CMake:CPackPackageGenerators#DEB_.28UNIX_only.29) for creating deb files via cmake. You might need to do a little more looking up than just that though.
