### ISSUE TITLE
Find a good way to run test plays without defense

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#366]
Right now we have to comment out lines of code to make this happen

**Comment by jcarn** [comment]
I'd be interested in this, which files does this involve?

**Comment by jgkamat** [comment]
This would be a semi-major restructure, but doing it would help you learn a lot about the play framework.
[this is our basic offense play](https://github.com/RoboJackets/robocup-software/blob/33a3b43f5f9b04c72b234fd3a1b473a800990f21/soccer/gameplay/plays/offense/basic_122.py). [This is where the current defense plays are added](https://github.com/RoboJackets/robocup-software/blob/33a3b43f5f9b04c72b234fd3a1b473a800990f21/soccer/gameplay/plays/offense/basic_122.py#L52). Currently we add the defense tactic to plays that need defense, like shown on that line. We probably should find a way to have plays explicitly request defense from the assigner (and the assigner could choose whether to fulfill that request or not).

**Comment by jcarn** [comment]
Are there any plays that we want to ignore the UI telling it to Use/Not Use defense?

**Comment by justbuchanan** [comment]
There are a couple test plays that don't really make sense with defense disabled, but I think when we want to run those, we can just make sure the defense checkbox is checked.
