### ISSUE TITLE
Fix role assignments for defense

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#368]
The defenders switch places when threat priorities change.

**Comment by justbuchanan** [comment]
This happens because sometimes the straight-line distance from robots to target points produces a different ordering than it should.  The solution is to use the estimated travel time instead of straightline distance when calculating assignment cost.  This is tricky though because travel time estimates can be more expensive to calculate...

**Comment by ashaw596** [comment]
I think it would still be worth it to explore how this type of "estimate"
to be exposed through the path planner api. It would be helpful for a lot
of problems like this

**Comment by justbuchanan** [comment]
One thing to keep in mind though is that right now role assignment runs at 60Hz and this estimate would be run (# robots)*(num roles that specify a position) times per iteration.  The path planner is expensive to run and even if we had a nice way to calculate a path and estimate travel time, we probably wouldn't want to use it here for performance reasons.  I think rough estimates should do fine here, so maybe just using the estimate from a trapezoidal velocity profile would suffice.

**Comment by justbuchanan** [comment]
On second thought though, the assignment issue with defenders happens because the estimate ignores obstacles, so the trapezoidal motion profile approach wouldn't solve this...

**Comment by ashaw596** [comment]
If you want to try trapezoidal estimates it is exposed now in the
robocup-py file

**Comment by ashaw596** [comment]
Though yeah that wouldn't be any different from nearest robot really
