### ISSUE TITLE
Don't attempt to score right away on indirect kicks

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#369]
Right now we do, which would count against us if we were able to make it.  The ball must touch another robot before we can score.

**Comment by jgkamat** [comment]
I think I can do this. It seems that both indirect and direct kicks are handled by OurFreeKick (as far as I can tell). How would I check to see if we are doing an indirect kick or not?

**Comment by justbuchanan** [comment]
Sounds good.  I don't know all of the details offhand, but there's a section on indirect kicks in the rules that has the info: http://wiki.robocup.org/images/1/18/Small_Size_League_-_Rules_2016.pdf.

**Comment by jgkamat** [comment]
oh, I was asking about finding it more programmatically, do we have it in the c++ side somewhere yet? I would assume its sent to us from the ref.

**Comment by justbuchanan** [comment]
Something like [this](https://github.com/robojackets/robocup-software/blob/master/soccer/GameState.hpp#L85)?

**Comment by jgkamat** [comment]
Perfect, thanks!

I probably should have looked in that file before
