### ISSUE TITLE
Redo configuration system

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#37]
Some things that would be nice:
- Remove the static variable dance that we currently do to register config values
- make config stuff easily accessible from python
- cascading
- auto-reloading when files change
- robocup-independent so it can be easily used in IGVC, IARRC?, etc

**Comment by jgkamat** [comment]
Now that we're building vartypes anyway, we might want to take another look at this. I don't think it's worth the effort though, although it would be nice!
