### ISSUE TITLE
Make capture choose a robot close to the intercept point

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#375]
Capture moves the robot to an intercept point along the ball's trajectory if it is moving, so the role_requirements() method should specify that point as the preferred bot location, not the ball's current location.  This may be best as a custom cost function since it's robot-dependent.

**Comment by ashaw596** [comment]
I did try that once and it caused some strange assignments at times but we
should try it again now that we have more time. If possible I'd also like
to change capture to actually intercept the ball (block it) if it has time.
