### ISSUE TITLE
osx-setup requires homebrew and homebrew cask to be installed first.

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#383]
It might also need xcode dev tools???

Can be done with 

```bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install caskroom/cask/brew-cask
```

**Comment by justbuchanan** [comment]
Good point.  It needs the xcode dev tools package too, right?

**Comment by ashaw596** [comment]
Oh yeah. I think? I haven't tried it without it. I installed xcode dev first lol to get git.

**Comment by justbuchanan** [comment]
Makes sense.  I think installing xcode will have to be done without the help of the setup script, but maybe we can put in a check for it at the top and print an error message if they don't have it installed.

I'll go ahead and add cask to the packages list.
