### ISSUE TITLE
Write ATtiny code for interfacing with the kicker board

### ISSUE THREAD

**Issue by jjones646** [RoboJackets/robocup-software#397]
We'll need an SPI slave interface written so we can communicate back to the mbed. This should be setup so it uses the same polarity & phase as that of the radio for simplicity.

**Comment by justbuchanan** [comment]
@jjones646, @ryanstrat, when will these boards be ready to be programmed?

**Comment by ryanstrat** [comment]
We finished soldering the first one yesterday. We should be able to give
this a try on Sunday


Ryan Strat
ryan@str.at
(678) 517-3393
RoboJackets | RoboCup Project Manager
Georgia Institute of Technology
