### ISSUE TITLE
Enable support for interrupts on the digital IO expander

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#400]
The io expander (mcp23017) has 8 inputs and 8 outputs.  We need to set up a system to interrupt the mbed when one of the input lines change.

cc @jjones646

**Comment by justbuchanan** [comment]
@jjones646 What's the status on this?

**Comment by justbuchanan** [comment]
@jjones646 is this something that we'll need or should I close this?

**Comment by jjones646** [comment]
We'll need this.

**Comment by justbuchanan** [comment]
How would something like this work?  It's connected via i2c, so what line(s) serve as the interrupt?

**Comment by jjones646** [comment]
There's another line for the interrupt itself - should be defined in the pin declarations file. It's a fairly trivial thing to do, but the lack of testable hardware is definitely the burden here.

**Comment by jgkamat** [comment]
Closing due to timeout (and that this is firmware, not robocup-software).
