### ISSUE TITLE
Fix game state issues in KickPenalty play

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#407]
The [KickPenalty play](https://github.com/RoboJackets/robocup-software/blob/master/soccer/gameplay/plays/restarts/kick_penalty.py) has a in_penalty class variable that gets set to True at some point, then never unset (as far as I can tell).  It seems like sort of a hack to work around limitations in our GameState object.

**Comment by barulicm** [comment]
Looks like this was a half-implemented attempt to manage the score function. I've changed the play to take advantage of the fact that restart plays are only enabled during restarts, which removes the need for the in_penalty member.
