### ISSUE TITLE
Implement BehaviorSequence

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#438]
We already have a class for this, but it isn't fully implemented and isn't used anywhere.  It needs to be rethought a bit and used in a couple places.  The main idea is to give a list of behaviors and have it run one after another.

**Comment by jcarn** [comment]
I'll check this out. @jgkamat if you are at core tomorrow could I talk to you about this there?

**Comment by jgkamat** [comment]
This is actually a pretty neat concept (probably taken from game AI). It might make it easier for new members who have no idea how to use FSM's build plays. 

I'll talk to you at core @jcarn, but I'm +1 on doing this!
