### ISSUE TITLE
Add .gitmodules file to setup script checksum for circleci

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#461]
Looks like changes to submodules are breaking some ci builds because the base image isn't being rebuilt.  This is the case for the [ninja branch](https://circleci.com/gh/RoboJackets/robocup-software/576) at the moment.

**Comment by jgkamat** [comment]
This is solved by #460, I'll merge it later today (you could pull from it into the ninja branch). Keep in mind though that the [gitmodules file](https://github.com/RoboJackets/robocup-software/blob/master/.gitmodules) dosent change when submodules are *updated*, (no sha in the file). I don't know where the actual sha is stored though.

**Comment by justbuchanan** [comment]
Cool, sounds good.  The SHAs are stored at the path of the submodule itself (some sort of weird file voodoo).
