### ISSUE TITLE
ccache w/ clang not working on ccache in ubuntu 14.04

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#466]
Lately the build's haven't been getting cached (via ccache), and I think I've found the issue, When I run ccache on ubuntu, it dosen't seem to be caching properly, but after upgrading to ccache 3.2.3, everything seems to work.
[the ccache docs](https://ccache.samba.org/releasenotes.html#_new_features_and_improvements_3) seem to say 'they fixed some clang issues' in 3.2

Not sure what to do about this...

**Comment by jgkamat** [comment]
4d7d9ecbd0be294058a6f1409e3c0cc25935b28c fixes this. 3.1.11 does not seem to work either...

**Comment by justbuchanan** [comment]
Oops, didn't mean to close this.  I don't see a good solution here unfortunately...  There's no repos for getting this version of ccache on ubuntu from what I can tell.  Also, my ubuntu vm is defaulting to the old g++ even after g++-4.9 is installed, which breaks the build - I'll open a separate issue for that.

**Comment by eis** [comment]
For future readers:
ccache only gained official support to clang in 3.2, see https://bugzilla.samba.org/show_bug.cgi?id=8118 for details.
