### ISSUE TITLE
MBED text output blinks...

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#476]
It's impossible to read anything

**Comment by jjones646** [comment]
I though it gave a nice touch to everything...

I just looked at the logs and it's actually coded to blink...and I made the commit. Don't remember that one.

For real though, it's switching the comments in [Console.cpp:325](https://github.com/RoboJackets/robocup-software/blob/robot2015-firmware/firmware/common2015/modules/Console/Console.cpp) or change the `5m` to `0m` at the end of 325.

**Comment by justbuchanan** [comment]
Haha I love finding commits I don't remember making.  Want to push that change to `robot2015-firmware`?

**Comment by jjones646** [comment]
Yeah I'll take care of it and then close this.
