### ISSUE TITLE
On Arch, only install AUR packages if they're not already installed

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#482]
Right now, every time I run `arch-setup`, it reinstalls all AUR packages.

**Comment by jgkamat** [comment]
shouldn't `--needed` do this for us (we already have this in our script but it dosent seem to be working)? Its weird that its not...

**Comment by justbuchanan** [comment]
Pacman has a `--needed` flag, but yaourt doesn't :/
