### ISSUE TITLE
Create basic sounds for the robot's speaker

### ISSUE THREAD

**Issue by jjones646** [RoboJackets/robocup-software#493]
- [ ] script to convert audio files to the appropriate file format
- [ ] add instructions to docs/readme for how to add new songs
- [ ] add GT fight song
- [ ] song commands

**Comment by jgkamat** [comment]
@joshhting

**Comment by ra4king** [comment]
@jjones646 Is writing audio data using an interrupt-based mechanism the most efficient way of playing audio? A 44.1 KHz audio source would have to have its interrupt fired 44,100 times a second!

**Comment by jjones646** [comment]
Well, it all comes down to how much we value audio - and the tradeoff of quality with system resources. The main issue is that it has to play nicely with the rtos setup, so I'm not sure if other approaches would work out.

**Comment by justbuchanan** [comment]
@ra4king how far were you able to get on this?  And do you think you'll be able to get it finished somewhat soon or should we try and find someone else to work on it?

**Comment by jgkamat** [comment]
Closed in favor of rj/robocup-firmware's issue, linked above.
