### ISSUE TITLE
Pressing up arrow (and other characters) breaks robot terminal

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#494]
When `screen`ed into a robot terminal, some characters cause it to no longer accept input, requiring a reboot.

**Comment by jjones646** [comment]
this is fixed in [712f3e3](https://github.com/RoboJackets/robocup-software/commit/712f3e3125b24b8829a8d99bd575b93bc44edb30#diff-beca703c744710d43042aa0750f666ad).

**Comment by justbuchanan** [comment]
:+1:
