### ISSUE TITLE
Soccer UI vibrates because of different font width of timer numbers

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#498]
Occurs on my laptop which is OSX el capitan

**Comment by jgkamat** [comment]
Font is different on my system, and I don't see this issue, so it's a font problem.

**Comment by justbuchanan** [comment]
Yeah sounds like a font issue.  I don't see this problem on my Mac, but I'm still on Yosemite.

**Comment by jgkamat** [comment]
![2017-01-13-011123_535x78_scrot](https://cloud.githubusercontent.com/assets/4349709/21920148/386ad868-d92d-11e6-9e02-32f930f967fe.png)

This is still an issue for me, at these numbers above. The font is monospace, so I've got no clue why it's doing this. Sounds like a good beginner issue for someone interested in UI.
