### ISSUE TITLE
Add legit radio test-rx

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#508]
Right now it's a loopback test where a packet is placed in the rx buffer, then read back again.  This is a good test that the radio interface works, but doesn't actually test rx.

cc @jjones646

**Comment by jjones646** [comment]
@justbuchanan I added a `loopback` test to the `radio` command a while back. Increase the log level a bit and you can see it doing the full ack sequence. So `test-rx` can be changed to an actual air packet now without losing this.

`radio loopback <message>`

**Comment by jjones646** [comment]
@justbuchanan Are the new commands stable enough so this can be closed?

**Comment by justbuchanan** [comment]
Yeah I think so.  I'll merge my PR that changes to the DISCOVER port into the firmware branch.
