### ISSUE TITLE
Soccer stalls randomly

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#513]
For me, it stalls randomly while soccer is running.
I'm running on Capitan in sim mode.

**Comment by ashaw596** [comment]
@justbuchanan Is this happening to you guys or is it just me?

**Comment by ashaw596** [comment]
Seems to just be role assignment issues. Something to do with INFO:root:SingleRobotCompositeBehavior: robot changed, restarting behavior

**Comment by justbuchanan** [comment]
Hmm, haven't had an issue on my Mac.  I'm not on Capitan yet though, but I'll be upgrading soon.  I'll let you know if I have any issues.

**Comment by jgkamat** [comment]
I'm not seeing this either.
