### ISSUE TITLE
debugThrow() should log errors

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#518]
Right now if we change the flag so that calls to `debugThrow()` don't raise exceptions, there's no way to know if something failed.  We should have it log info to `stderr`.

**Comment by ashaw596** [comment]
Makes senses.

**Comment by ashaw596** [comment]
Commit ba35c0d implements it. I meant to do a pull request, but I accidentally pushed to master. Well, nothing radical changed so....

**Comment by justbuchanan** [comment]
:+1:
