### ISSUE TITLE
Rect.hit() isn't quite right

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#528]
cc @ashaw596

**Comment by barulicm** [comment]
@ashaw596 Can you elaborate on this? I took a look at it last night and added more tests, but don't see any significant errors in the code.

**Comment by ashaw596** [comment]
Yeah, nvm, I just looked at it again and I think the logic works fine after commit 5b1ff5b is merged which adds Robot_radius and fixes the bugs in nearSegment. I thought some more weird stuff was still going on in nearSegment, but I think all the cases are covered. Its just a bit weird.
