### ISSUE TITLE
Add a docs page for coding/naming conventions

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#557]
I think we used to have an example C++ file demonstrating naming conventions of variables, instance variables, classes, methods, etc.  I'm not sure where it is though...  It would be helpful to have a reference for this type of thing on our docs site.

We also could just link to the google style guide and put a short summary on our site.

**Comment by jgkamat** [comment]
I've started this [on this docs page](https://robojackets.github.io/robocup-software/md_doc_Style.html). Let me know if you want to help, or just submit a PR.

**Comment by jgkamat** [comment]
Could need a bit more work but this should be at least a good starting point.
