### ISSUE TITLE
`make robot2015-gdb` should ask which mbed to use when multiple are connected

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#573]
Right now it just fails when more than one MBED is connected, it would be nice if it asked which one to use.

cc @jjones646

**Comment by jjones646** [comment]
[Here's](https://github.com/mbedmicro/pyOCD/pull/221) some things that the developers for pyOCD pointed towards.

**Comment by jgkamat** [comment]
Closed in favor of rj/robocup-firmware's issue, linked above.
