### ISSUE TITLE
Reorder role assignment and composite behavior execution?

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#58]
@barulicm This is the issue you brought up earlier - I hit it myself when implementing RepeatedLineUp.

The play has three states: left, right, and pause - the ideas was to make the robots run laps, but pause for a second or two once lined up, then go to the other side.

When it goes from `pause` to `left`, it adds a tactics.line_up subbehavior.  The next loop around, the play's spin() gets called before role assignment takes place, then it transitions immediately back to `pause` because the LineUp tactic reports that it's completed because it has no robots...

**Comment by kfu02** [comment]
old
