### ISSUE TITLE
Fix travis-ci failing

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#581]
It's failing because the `osx-setup` script is taking too long, so travis-ci times out and kills it.

**Comment by justbuchanan** [comment]
travis-ci now supports caching on OS X, so once we set that up, our problems should be fixed.  Shouldn't be too hard to do.

https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone

**Comment by jgkamat** [comment]
Moving this to wishlist, since we don't have a Mac OS Maintainer right now.

**Comment by guyfleeman** [comment]
We haven't had a maintainer for soccer on OSX for a long time. I'm closing this unless you're opposed @jgkamat

**Comment by jgkamat** [comment]
Sounds like a good idea to me ;)
