### ISSUE TITLE
Improve ball filter

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#6]
We use a Kalman filter to model the motion of the ball.  The Kalman filter accepts readings from the cameras and adjusts its state based on those readings and a physical model of the ball.  The physical model of the ball doesn't know when the ball has been kicked and gets thrown way off when it happens.  This severely affects our ability to receive passes.  We need to let the ball filter know when kicks happen so that we can compensate.

**Comment by justbuchanan** [comment]
@ashaw596, there's some Kalman Filter stuff in the [old folder](https://github.com/RoboJackets/robocup-software/tree/master/old/modeling-old) that might be helpful for this.

**Comment by JNeiger** [comment]
Closing in favor of #1202
