### ISSUE TITLE
Fix race condition in soccer

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#607]
Not sure what the cause is yet, but occasionally (not always) soccer crashes at startup with this error message:

~~~{.sh}
Traceback (most recent call last):
  File "/home/justin/src/rj/robocup-software/soccer/gameplay/play_registry.py", line 298, in data
    return str(node.play_class.score())
  File "/home/justin/src/rj/robocup-software/soccer/gameplay/plays/offense/basic_122.py", line 58, in score
    return 10 if main.game_state().is_playing() else float("inf")
AttributeError: 'NoneType' object has no attribute 'is_playing'
/bin/sh: line 1: 14152 Aborted                 (core dumped) ./soccer
makefile:24: recipe for target 'run' failed
make: *** [run] Error 134
~~~

note: this can be reproduced by putting a small delay in `USBRadio.open()` and having a radio connected.

**Comment by chachmu** [comment]
The main.game_state ultimately gets called from inside processor.run() after running some code to set up the radio. I think if the delay for setting up the radio is long enough, it keeps the creation of main.game_state from happening until after main.cpp calls processor->gameplayModule->loadPlaybook which is causing this error.
