### ISSUE TITLE
ls command in firmware is broken

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#610]
Here's what I get when I run it:

~~~{.sh}
Justin Buchanan@robot $ ls

ls:
    Description:        List contents of current directory
    Usage:              ls
Justin Buchanan@robot $
~~~

Any ideas @jjones646?

**Comment by jjones646** [comment]
[Here's](https://github.com/RoboJackets/robocup-software/commit/65adfb7124b394d4f3b9ce87bce02432b5e9b5ad#diff-79205bd1f31748766e81beff91d5c9e5L51) the issue.

**Comment by justbuchanan** [comment]
:+1: good find.  I'll get this fixed.
