### ISSUE TITLE
Setup PID control in robot firmware

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#619]
Eventually we're planning to use an LQR controller (see PR #322), but it would be nice to have a PID controller setup in the meantime because it's much simpler to implement.

**Comment by jjones646** [comment]
https://developer.mbed.org/cookbook/PID

**Comment by justbuchanan** [comment]
Nice, that's a good resource!

Also for reference, we have a [PID class](https://github.com/RoboJackets/robocup-software/blob/master/common/Pid.hpp) in our codebase that we're currently using for soccer that we can also use in firmware.

**Comment by justbuchanan** [comment]
Initial work for this is on the [justin/robot-pid branch](https://github.com/RoboJackets/robocup-software/tree/justin/robot-pid).
