### ISSUE TITLE
Investigate QML for soccer UI

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#621]
Our current GUI setup is sort of tough to modify because re-arranging parts of the interface requires destroying a lot of the layout, then rebuilding it.  Another downside to our current setup is that if two people modify `.ui` files simultaneously, merge conflicts are pretty much guaranteed to happen.

Qt's newer system for building UIs is [QML](http://doc.qt.io/qt-5/qtqml-index.html), which looks pretty nice.  Not sure how tough it would be to switch to using it or if it's the best option for us, but it looks like it would let us build a much better UI much more easily.  It would also be significantly easier to modify.

**Comment by jgkamat** [comment]
After trying out QML on the rrt gui, I think this is not a worthwile investment because:

1. It's a lot of work, rewriting the whole UI
2. It's not fully functional, you can't even change button colors in QML

If someone wants to take point on this, reopen this issue.
