### ISSUE TITLE
Implement "self test" functionality for firmware

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#633]
The control board has a "self test" button on it that is intended to perform hardware checks and report if there are any errors.  It currently isn't setup to do anything, but we should write some code to make it functional.

@jjones646 any thoughts on exactly what this button should do?  We already have the red error leds set to light up for certain things, but a lot of those checks happen right now at startup and don't get checked again.  Maybe the button can just run the checks again and update the leds for any new errors that have happened since startup?

This might be a good place for the io expander's interrupt functionality (#597).  Polling works fine for the dip switches and radial selector, but polling could easily miss an instantaneous button press.

**Comment by jjones646** [comment]
Something that could be pretty useful would be to spin each motor ~1/4 turn in series - one at a time.

This also brings up what the dip switches will be used for too.

**Comment by jgkamat** [comment]
Closed in favor of rj/robocup-firmware's issue, linked above.
