### ISSUE TITLE
Measure battery voltage in firmware

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#634]
@jjones646 how is the ADC for this setup?

**Comment by jjones646** [comment]
It's just a voltage divider from the battery. Comes into one of the ADC pins on the mbed.

![vdivider](https://cloud.githubusercontent.com/assets/7342505/14501656/77da405a-0175-11e6-9fc1-038676748df5.png)

The min/max limits for the lipo are 16V and 21V respectively. So the ADC range is this with a linear relationship:
min: 0.621
max: 0.815

Those are pretty loose bounds, and it's a bad idea to operate motors outside that range.
