### ISSUE TITLE
Double-check field sizing against new SSL rules

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#638]
The new rules add a wall between where the refs walk and where the robots are.  We should double-check and make sure that the field border size we have set in `Field_Dimensions` matches the new setup.

**Comment by jcarn** [comment]
Is this using the 2015 rules? If it is using 2016 rules, where might those be located? The official page/official wiki only has up to 2015 but it looks a tad outdated.

**Comment by justbuchanan** [comment]
Yeah they switched the location of their wiki not too long ago, so google often points to the old one.  Here's the page with the 2016 rules:

http://wiki.robocup.org/wiki/Small_Size_League/Rules

**Comment by jcarn** [comment]
Ah gotcha, thanks
