### ISSUE TITLE
Fix ninja build warning about git_version.cpp

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#640]
This gets printed out at every build and is a little annoying.  There's probably something wrong in our CMake files.

~~~{.sh}
ninja: warning: multiple rules generate common/git_version.cpp. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
~~~

**Comment by jpfeltracco** [comment]
I ran `make clean && make` on both Arch and Ubuntu 16.04 with 209e1105b98de70713596a2f9a0054c0497bda8f and wasn't able to replicate.

Can someone else try this out and confirm so we can close this?

**Comment by jgkamat** [comment]
The relevant bit of cmake was in the firmware cmake lists, I'll migrate this issue over to firmware, and close this one.
