### ISSUE TITLE
Update 2015 firmware docs page

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#670]
It's pretty parse: http://robojackets.github.io/robocup-software/md_doc__robot_firmware2015.html.

Some of the info will have to wait until later when we get it all figured out, but there's definitely plenty we can add to it now.

**Comment by jgkamat** [comment]
Closing in favor of RoboJackets/robocup-software#1

Going to make a new issue to migrate those pages over though.
