### ISSUE TITLE
Firmware "screensaver" stops working after a few minutes

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#671]
The "screensaver"/imAlive lights on the MBED builtin LEDs work for a little while, then stop.  This may be related to PR https://github.com/RoboJackets/robocup-software/pull/588.

**Comment by jjones646** [comment]
I vote to reverse the "screensaver" back to something simple. Something that doesn't need the timing requirements that is used now.

**Comment by justbuchanan** [comment]
Sounds good.  How about just blinking one of the mbed's on-board LEDs?

**Comment by justbuchanan** [comment]
I changed the strobing effect to a simple flasher on mbed's LED1.  It still stops after a minute or two and I can't find out why... The timeout is set to `osWaitForever`.

**Comment by jgkamat** [comment]
Closed in favor of rj/robocup-firmware's issue, linked above (assuming this wasn't fixed at comp, if it was, feel free to close the linked issue).
