### ISSUE TITLE
CC1201 fails if other radios are transmitting when firmware boots up

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#672]
Maybe we need to flush buffers and strobe it into RX after everything initializes

cc @jjones646

**Comment by jjones646** [comment]
there's high speculation that it's due to the mbed missing the 1st edge triggered interrupt from the cc1201, but that hasn't been looked into yet.

**Comment by justbuchanan** [comment]
Relevant google doc: https://docs.google.com/document/d/1oop82J2OscGVAEYbQcU4IoGHz5mU44n06LuA0Ib1iaU/edit

**Comment by justbuchanan** [comment]
@jjones646 as of 293404dbee39, I think I have this all working!  You can see the commits for the full changes, but the highlights (that I remember) are:

* In `getData()`, I added an RX fifo flush if the radio says that no data is available
* In `CommLink.rxThread()`, the interrupt in is now registered *before* it waits for the call to ready().
* interrupt line is falling-edge triggered.  We've tried it both ways several times, but I've switched it to falling-edge and remove the `Thread::wait()` in `getData()` - everything seems to work
* removed all `SAFC` strobes.  On the transmitting side, I realized that it was sending this strobe whenever a *transmit* triggered an interrupt - I think this was causing it to calibrate according to bad data.  Removing this fixed the issue where the transmitter could only send ~5 packets before going out of calibration.  We may want to add calibration back in for valid RXs, but it's working fine without them for now.

**Comment by justbuchanan** [comment]
Success!  The robot shows up and stays in soccer.

![2016-05-22-212101_1920x1080_scrot](https://cloud.githubusercontent.com/assets/115131/15458084/7904d5b4-2063-11e6-9daf-410ad526f790.png)

**Comment by jjones646** [comment]
:clap:

> interrupt line is falling-edge triggered. We've tried it both ways several times, but I've switched it to falling-edge and remove the Thread::wait() in getData() - everything seems to work

Awesome! :+1: This is with the interrupt pin being configured with `0x06`?

> removed all SAFC strobes. On the transmitting side, I realized that it was sending this strobe whenever a transmit triggered an interrupt - I think this was causing it to calibrate according to bad data. Removing this fixed the issue where the transmitter could only send ~5 packets before going out of calibration. We may want to add calibration back in for valid RXs, but it's working fine without them for now.

I can't believe we overlooked something like this for so long. Now that you've pointed it out, everything is starting to make some kind of sense!

**Comment by justbuchanan** [comment]
Yep, it's at `0x06`, it may need to change though (#677).

Yeah in hindsight it should have been obvious...  Glad it's finally fixed though, we should be able to move onto more fun stuff now!
