### ISSUE TITLE
Tune ball placement behaviors

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#676]
Ball placement works fairly well in the simulator, but will need some tuning in order to work with actual robots.  It could also use a little tuning to be more effective in the simulator.  See PR https://github.com/RoboJackets/robocup-software/pull/651

**Comment by chachmu** [comment]
When I actually get around to doing this I will also try to make the play handle getting another stop command in a way that doesn't completely break everything.

**Comment by jgkamat** [comment]
Can this be closed or do we need another round of this? (I don't know if ball placement is a challenge again?)

**Comment by chachmu** [comment]
If we ever want to actually use this we will definitely need another round of tuning but if it doesn't come back up I doubt we would ever use it since the only way to activate it is to have both the external referee and the remote terminal open.
