### ISSUE TITLE
CC1201.getData() is called for both rx and tx

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#677]
It's really only intended to be called on RX.  We should either find a way to prevent it from being called in TX or update our method documentation a bit to clarify that it gets called for both.

cc @jjones646

**Comment by jjones646** [comment]
I'm assuming this is related to when the interrupt pin config is set to `0x06`.

Linking the [radio doc](https://docs.google.com/document/d/1oop82J2OscGVAEYbQcU4IoGHz5mU44n06LuA0Ib1iaU/edit) for more reference to this issue.

**Comment by justbuchanan** [comment]
Yeah we're set to 0x06, it might be worth messing around with trying the CRC_OK signal or the other similar one.
