### ISSUE TITLE
Motors burn if duty cycle abruptly drops from ~350+ to 0

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#681]
@jjones646 and I ran fb9365568fbb4e1df6694579ed51281015bc974c and had a motor burn out :fire:.  We suspect that the cause was that the motor was spinning very fast (duty cycle ~350), then we rebooted the mbed, causing the fpga's watchdog to timeout and set the duty cycle to zero.  The motor stopped very quickly and started smoking.

**Comment by jjones646** [comment]
I think the bulk of this is fixed in d97f29b. Still not 100% confident about all of it, but it should be something in the right direction.
