### ISSUE TITLE
Use serial silicon id chip for radio uid

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#684]
Right now the robot's uid is hard-coded to `2` in `main.cpp`.

**Comment by justbuchanan** [comment]
I setup the hex selector for radio comm in 18b5410, which is now on master.  I think the serial silicon uid stuff probably won't happen for this comp.

**Comment by jjones646** [comment]
next year

**Comment by jgkamat** [comment]
Closed in favor of rj/robocup-firmware's issue, linked above.
