### ISSUE TITLE
Robot does not show sometimes in Soccer

### ISSUE THREAD

**Issue by jjones646** [RoboJackets/robocup-software#691]
So here's when it happens:

Soccer is running, robot is on, and the manual id is selected for controlling with the joystick. Everything is in a working condition, and you can see the robot in Soccer. Now, unplug and plug back in the base station. The robot won't show up in the GUI, but you can still control it.

**Comment by justbuchanan** [comment]
Closed in e419fc4b801a13f129adb70b45f6d81c98f6957f and d982880ee8606dcd5720bf725abf829a37f19735
