### ISSUE TITLE
Build not working on 14.04

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#696]
It looks like an issue with the gcc package for firmware.  I created the `justin/ci-test` branch to track down the issue - it's the same as master except with an extra line appended to `ubuntu-setup` to trigger a rebuild of the CI image.  Here's the error:

~~~{.sh}
WARNING: The following packages cannot be authenticated!
  gcc-arm-none-eabi
E: There are problems and -y was used without --force-yes
[ERR] Your setup command FAILED. Exiting...
/home/ubuntu/robocup-software/external/DoCIF/util/maketest.sh: line 90: cd: /home/developer/project: No such file or directory

./external/DoCIF/commands/buildbaseimage.sh returned exit code 1

Action failed: ./external/DoCIF/commands/buildbaseimage.sh
~~~

**Comment by jgkamat** [comment]
I think terry guo has decided to exact his/her revenge :/

Their repo is now private. They pulled a leftpad on us.

**Comment by justbuchanan** [comment]
Dammit Terry...  I guess we need to find a new repo :package:

**Comment by jgkamat** [comment]
In the interim, we can pull the one in the debian repos :wink: 

I'll see if that works, give me a sec

**Comment by jgkamat** [comment]
Hmm, it seemed to complain about missing files (even though the headers actually exist). I think this is because I'm mixing trusty/yakkety dependencies. I'll try again properly sometime tomorrow.

**Comment by justbuchanan** [comment]
Ok sounds good.  Thanks for looking into this!

**Comment by jgkamat** [comment]
I think terry guo is a wizard and made a custom build that would work on 14.04, anything that I do dosen't seem to work 100%

I think the best course of action right now is to switch the CI to 16.04 (which builds at least the main build), since we need to do that later eventually. If anyone has the deb files that were distributed by terry guo, that would work too...

**Comment by jgkamat** [comment]
https://github.com/RoboJackets/robocup-software/tree/jay/16.04: the 16.04 build works fine. Still would be nice to stay on 14.04 until after comp though

**Comment by justbuchanan** [comment]
Haha yeah I messed around with some alternative gcc arm packages too and I can't get anything to work.

Switching to 16.04 is probably the easiest course of action since we're planning to do that after comp anyways.  It's fine by me if you want to go that route.

**Comment by jgkamat** [comment]
Turns out the repo didnt get deleted, its just moved over here: https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa

I'll add a PR to fix this hopefully.

**Comment by jgkamat** [comment]
https://circle-artifacts.com/gh/RoboJackets/robocup-software/2204/artifacts/0/tmp/circle-artifacts.XWN3nrY/compile.txt

It seems like this newer version is causing the same errors I've been seeing. Any ideas? :/

**Comment by justbuchanan** [comment]
Darn :/.  There's probably a way to fix it, but if the 16.04 version works fine, I'd just go with that.

**Comment by jgkamat** [comment]
@ryanstrat needs 14.04 support, so i'm reopening this

**Comment by jgkamat** [comment]
Going to start dumping things for myself here:
https://github.com/platformio/platformio/issues/301
