### ISSUE TITLE
LineUp play sends the robot off-field

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#712]
When running soccer with ssl-vision in the shop, the LineUp play tried to send the robot off of the side of the field.  See the picture below - the path's end is out of bounds.  Haven't looked into it too much yet.  Maybe something to do with the field geometry being wrong?

![2016-06-15-233018_1332x1034_scrot](https://cloud.githubusercontent.com/assets/115131/16104715/bbddcc1e-3351-11e6-8715-ff0bd42bde82.png)

cc @jgkamat

**Comment by jgkamat** [comment]
This might be related to the vision packet resizing I made? But those changes should show up in the window too. 

I cant reproduce this in the simulator, is this on the real field?

**Comment by jgkamat** [comment]
![snapshot2](https://cloud.githubusercontent.com/assets/4349709/16125006/7cdb785e-33a6-11e6-9e1d-23167b5ce9be.png)

The coordinates on your screen are the same as mine, so maybe the geometry resizing made the field smaller?

**Comment by jgkamat** [comment]
If you comment out this line, does it work?
https://github.com/RoboJackets/robocup-software/blob/master/soccer/Processor.cpp#L305

I don't think theres a way to run the simulator on the same port as the vision (so I cant try a resize and then run the simulator)
