### ISSUE TITLE
Coordinated_pass freezes occasionally

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#719]
When I run coordinated pass, it sometimes freezes, with the kicker kicking, but not actually moving towards the ball (without contact). I don't know if this is an issue in path planning/motion control or not.

If I nudge the robot towards the ball, it kicks it just fine.

![snapshot3](https://cloud.githubusercontent.com/assets/4349709/16173547/e9dd9e24-3558-11e6-94b8-cceae68cf354.png)

**Comment by chachmu** [comment]
I'm guessing that's path planning because I have been having that same issue for a while with multiple different plays.

**Comment by justbuchanan** [comment]
@ashaw596 can you look into this and see if it might be path-planning-related?

**Comment by ashaw596** [comment]
Its probably cause, I removed the requirement to not lose contact with the ball during pivot kick. I'll work on it.

**Comment by ashaw596** [comment]
I couldn't really get reproduce the bug on my computer, but I changed aim to fumble if it loses contact again. It should fix it (theoretically) and doesn't seem to cause much issues.
