### ISSUE TITLE
Re-enable robot rx/tx LEDs

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#745]
I disabled them in https://github.com/RoboJackets/robocup-software/commit/e8d59dd8b9ea5e37d0d6e1b417e065dd4b80d5fd b/c something related to having too many timers seems to cause the mbed to crash and reboot.

**Comment by jgkamat** [comment]
Closed in favor of rj/robocup-firmware's issue, linked above. This is probably already fixed, if so, close the firmware issue or let me know.
