### ISSUE TITLE
Soccer should look for the "logs" directory relative to the "run" directory

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#754]
Right now it looks relative the current _working directory_.  This is an issue because if you launch it with `./run/soccer` from the root of the repo, it looks for `./logs` which probably doesn't exist.  This is why we failed to log our first match at comp.

**Comment by chachmu** [comment]
This also seems to apply to the option to create a log folder under debug, I think it uses the same variable though so changing that should fix it.

**Comment by jpfeltracco** [comment]
[Relevant Code](https://github.com/RoboJackets/robocup-software/blob/6d6947842789e90c67462b7fcbe8a21d8951764c/soccer/main.cpp#L157)

**Comment by jgkamat** [comment]
Currently, the makefile cd's inside the run folder before running soccer when using `make run`, so anyone working on this, just change the logs dir in the two places in the referenced code, and test it out by manually running `./run/soccer`. I'll add the makefile changes once a PR is made, unless the assignee wants to stab at that too.

**Comment by rachitk** [comment]
Just made a PR #835 to make the change requested. Not positive if it's the correct change or if it's fully complete yet, as `make run-sim` does not log properly with this change, likely due to makefile changes still needing to be made.
