### ISSUE TITLE
Restarting single robot behaviors isn't always the best thing to do

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#755]
In coordinated pass, if the receiver is temporarily assigned to a different robot (which happens occasionally), the receiver gets restarted, which messes up coordinated pass transitions, causing the pass to hang indefinitely.

Restarting a single robot behavior when a new robot is re-assigned is often the correct thing to do, but not always.  This needs some thought.

**Comment by jgkamat** [comment]
Could we just swap out the robot for a singleRobotBehavior without restarting it (if requested by the behavior, probably in its constructor). This is pretty important imo, especially for pass receives.

**Comment by chachmu** [comment]
We could give behaviors a bool that would determine if they should restart on being transferred to a different robot then just check it to see if we should restart here in [SingleRobotCompositeBehavior](https://github.com/RoboJackets/robocup-software/blob/c89da1b7f75e8b28e0aee0cff80630db115ba02b/soccer/gameplay/single_robot_composite_behavior.py#L58).

**Comment by jcarn** [comment]
I'll look into this and #756

**Comment by jcarn** [comment]
Is there a specific circumstance in which this happens? So far its handling everything fine, I can't get it to hang
