### ISSUE TITLE
Robot labels in soccer are a little too big

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#757]
cc @ashaw596.

**Comment by jgkamat** [comment]
:+1:, the bigger size is better but this is a bit too big.

**Comment by jgkamat** [comment]
https://github.com/RoboJackets/robocup-software/blob/master/soccer/FieldView.cpp#L512

**Comment by rachitk** [comment]
Did a bit of testing on my own and it seems that changing the numbers to (0.0131, -0.0131) makes the labels almost perfect (in my opinion). Didn't want to submit a pull request since you might be saving this for training; just a reference for anyone interested in fixing this.

**Comment by jgkamat** [comment]
@rachitk go ahead and submit the PR! If you need help with it, just email me/ ask on gitter/ or ask during training! Thanks for taking the initiative :smile:
