### ISSUE TITLE
When using external ref, goalie id should be pulled from ref packet

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#761]
This will ensure that we're using the correct goalie that we told the referee we would use.

**Comment by chachmu** [comment]
In order to tell the root_play to assign the goalie id from the ref packet, the id needs to be passed from c++ to python somehow. Would it be better to put that in GameState or in SystemState? I would think GameState from what I have seen but I'm not really sure.

**Comment by chachmu** [comment]
Never mind, turns out the our referee number is stored in ourTeamInfo inside GameState
