### ISSUE TITLE
Defense should ignore shot obstacle during test plays

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#763]
This could be done with a fairly quick hack, but it would be nice to have a more flexible obstacle system so that this and other obstacles can be made to apply only to certain robots.  Somewhat relevant to #758.

**Comment by chachmu** [comment]
If we are fixing this we should probably also look into making the defense see the robot shooting at the goal as a danger. Currently our defenders do not mark the test robot during test plays so we can't see how well the play works against defense and vice versa.
