### ISSUE TITLE
Playbook load in soccer should show file chooser in the correct folder

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#764]
Right now it shows the root of the project, it should launch to `soccer/gameplay/playbooks`.

**Comment by jpfeltracco** [comment]
[Relevant function](https://github.com/RoboJackets/robocup-software/blob/a10654f07fdf73f2951ae9a0081b865a23102880/soccer/gameplay/playbook.py#L7)

[Relevant call to function](https://github.com/RoboJackets/robocup-software/blob/a10654f07fdf73f2951ae9a0081b865a23102880/soccer/gameplay/main.py#L147)

**Comment by jgkamat** [comment]
So the reference above is for the actual loading of the file, for the file chooser you will need to look at [this bit of code](https://github.com/RoboJackets/robocup-software/blob/6ea6cf696dd5ecd7caca044bee93a308cea32e5c/soccer/MainWindow.cpp#L1203). However, this already works when running soccer from the run directory. See #754 as well.

I think all paths should be relative to the root of robocup-software, so I'm in favor of changing the `../soccer/gameplay/playbooks/` to `./soccer/gameplay/playbooks/`, and swapping it over in the makefile. If you want to tackle this issue, go ahead and do the above for now.

This relative/absolute path is starting to get kind of annoying, so I'm going to open another issue for it.

**Comment by rachitk** [comment]
Made the change in #835 as requested; no changes have been made to makefile yet, so `make run` and the like now do not work while `./soccer/run` does.
