### ISSUE TITLE
Create a Competition Mode

### ISSUE THREAD

**Issue by chachmu** [RoboJackets/robocup-software#778]
Would it be a good idea to make a mode for competition (maybe "make run-comp") that restarts itself if it crashes and maybe defaults to logging somewhere to keep us from forgetting to log? This would require the completion of #762 but it would help solve a lot of our issues with seg faults during competition or other problems.

**Comment by jgkamat** [comment]
Once we have arguments that load playbooks and stuff like that, we can just add a target in the makefile with a bit of shell script that would do this for us. It shouldn't be too hard once the actual functionality is implemented.

**Comment by guyfleeman** [comment]
Maybe some safety checking like external ref mode and behavior tree view. I know we forgot these sometimes at comp, and I don't think in the heat of the moment people will actually care about a checklist.

**Comment by chachmu** [comment]
Behavior tree view and external ref are the default already so when soccer relaunches we wouldn't need to worry about that. The make command would need to take arguments for which side of the field to defend and maybe if we are blue or yellow. I know which team we are is supposed to be encoded in the ref packets but I'm not actually sure if that always gets set properly.

**Comment by ryanstrat** [comment]
The ref packets have team names and colors set 100% of the time at comp

**Comment by jgkamat** [comment]
Because of segfaults, this is a priority (implemented in some form, be it in c++ or in the makefile). Bumping priority up.
