### ISSUE TITLE
Team Labels in Soccer shouldn't have brackets.

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#824]
Currently, team labels in soccer say `<Yellow Team>` or `<Blue Team>`.

These labels shouldn't have brackets, but should be bold or underlined.

[See this snippet for where to change teamnames](https://github.com/RoboJackets/robocup-software/blob/6ea6cf696dd5ecd7caca044bee93a308cea32e5c/soccer/MainWindow.cpp#L432). This field accepts HTML tags to make it bold/underlined. Tweak it until it looks nice! 

![screenshot_20161127_174544](https://cloud.githubusercontent.com/assets/4349709/20652544/5a910922-b4c9-11e6-9705-ccf665647064.png)

**Comment by petschekr** [comment]
I'll take this
