### ISSUE TITLE
'Red Cards' label in UI stylesheet seems to be hardcoded for ubuntu

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#825]
It looks kind of wrong right now:

![screenshot_20161127_175027](https://cloud.githubusercontent.com/assets/4349709/20652589/fe06fa62-b4c9-11e6-950d-6c183efd5196.png)

You could fix this in qtcreator, but it's honestly easier to edit this file by hand instead. 

[This is the bad section of the ui file](https://github.com/RoboJackets/robocup-software/blob/6ea6cf696dd5ecd7caca044bee93a308cea32e5c/soccer/ui/MainWindow.ui#L1271)

[Here is a good section from the blue team's 'red card' section:](https://github.com/RoboJackets/robocup-software/blob/6ea6cf696dd5ecd7caca044bee93a308cea32e5c/soccer/ui/MainWindow.ui#L1113).

Should be enough to replace the broken one with the ok one, and readjust the colors to match yellow.

**Comment by krispreza** [comment]
Ill take this.

**Comment by EdwardTan20** [comment]
so this file will be rewritten or replaced?
