### ISSUE TITLE
Default Playbooks should include all restart plays

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#826]
Right now, we have a playbook load/save sytem, which can be activated with the buttons above the plays dialouge.

We load [this file by default](https://github.com/RoboJackets/robocup-software/blob/master/soccer/gameplay/playbooks/example.pbk).

This file should be modified to add all the plays under restarts. You can do this by editing the file by hand, or by checking all the plays, and saving to this file.

![screenshot_20161127_180112](https://cloud.githubusercontent.com/assets/4349709/20652669/7f9c3cda-b4cb-11e6-96f8-7f5207da9890.png)

**Comment by hchittanuru3** [comment]
I got dis
