### ISSUE TITLE
Python complaining about double initialized methods

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#828]
```
_frozen_importlib:222: RuntimeWarning: to-Python converter for OurRobot* already registered; second conversion method ignored.
_frozen_importlib:222: RuntimeWarning: to-Python converter for OpponentRobot* already registered; second conversion method ignored.
_frozen_importlib:222: RuntimeWarning: to-Python converter for SystemState* already registered; second conversion method ignored.
_frozen_importlib:222: RuntimeWarning: to-Python converter for std::shared_ptr<Configuration> already registered; second conversion method ignored.
_frozen_importlib:222: RuntimeWarning: to-Python converter for ConfigBool* already registered; second conversion method ignored.
_frozen_importlib:222: RuntimeWarning: to-Python converter for ConfigDouble* already registered; second conversion method ignored.
_frozen_importlib:222: RuntimeWarning: to-Python converter for ConfigInt* already registered; second conversion method ignored.
```
appears when running soccer.

This can be solved by [removing all instances of register_ptr_to_python in this file](https://github.com/RoboJackets/robocup-software/blob/4da80ab54496394212a0a618ff58ad10642a92cf/soccer/gameplay/robocup-py.cpp#L655). 

Right now I can't see any problems when we do this, but whoever's trying this should try and see if they can break any python stuff we have.

As far as I know these do nothing (hence the warning) as of now, so removing them shouldn't be an issue.

**Comment by Jason27chan** [comment]
got it

**Comment by jcarn** [comment]
Was this fixed? It still happens for me

**Comment by ashaw596** [comment]
Oh I undid the fix since it broke it on my mac.

**Comment by jgkamat** [comment]
Yah, we might want to figure out why mac needs this but ubuntu complains about it. I'm not sure what approach to take on this :/

**Comment by JNeiger** [comment]
Looks like the changes got reverted to Jason's branch. Imma close this.
