### ISSUE TITLE
Hall Faults should be renamed to Motor Faults

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#829]
We have a robot status panel on the left that shows us info about robot problems.

![screenshot_20161127_183415](https://cloud.githubusercontent.com/assets/4349709/20652865/1febfbcc-b4d0-11e6-9a41-7f8a43eb21d6.png)

Hall faults shouldn't be displayed as hall faults (@jjones646 says so, and it's more obvious anyway), but rather just generic motor faults.

[This is the critical section of code that needs to be changed](https://github.com/RoboJackets/robocup-software/blob/master/soccer/MainWindow.cpp#L591). The demo above doesn't really work, but you should change that from hall->motor as well.

**Comment by EdwardTan20** [comment]
I'll work on this
