### ISSUE TITLE
Repeated line up shoud provide an easy way to traverse only part of the field

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#830]
Repeated line up currently traverses the entire field, whcih is what we want by default.

However, during tuning, we may want to insert a buffer, to limit how far we command the robots to go, so if there is a problem, we won't bump into the walls.

[This should be easily achevable by changing the calls to gen_line here to decimal values](https://github.com/RoboJackets/robocup-software/blob/8aa13ff4334af3d8bba1f5e64febd36c311c8d38/soccer/gameplay/plays/testing/repeated_line_up.py#L54). However, it would be nice to have a single constant value at the top of the file to tune both of these gen line calls at once, so it's easy to do this in a rush.

**Comment by ashaw596** [comment]
Relevant idea which I just remembered to create an issue for #832

**Comment by rk1998** [comment]
ill take this
