### ISSUE TITLE
Establish convention for referencing files

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#831]
Right now referencing files in soccer is a mixed bag, and I want to try to standardize it so we don't have issues.

Currently, the convention is to assume we are running from the `./run` directory, so to get perfect behavior you need to: `cd run && ./soccer`. The makefile does this automatically with `make run`.

Here are different schemes I can come up with. Feel free to add some more

1. Keep the current scheme. Reference everything from the ./run/ folder, and force people to run from the ./run folder.
2. Switch to the root of the repo. this will force people to run our binary with ./run/soccer, and have their current directory be the root of our repo. We will need to change the makefile to reference this
3. Use relative paths everywhere, and establish a file which we won't move as our reference point. This is my favorite. In python/bash this is trivial, with `dirname` or `os.path.dirname(os.path.realpath(__file__))`, but in c theres no standard cross platform way to do this. I think we can use the python bridge to take advantage of the python binding to dirname, which should be cross platform. When we do this, all file references must be relative to the directory root which we define. This will allow people to run our binary from any current directory.

Let me know what you guys think!

Related: #754 #764

**Comment by rachitk** [comment]
Referenced this in #835. Made changes in `makefile` that has implications for this topic, and essentially makes all of the changes that option 2 requires. 

If option 2 is rejected in favor of another option, then #835 should NOT be merged.

**Comment by jgkamat** [comment]
https://github.com/RoboJackets/robocup-common/blob/950f393193f3cc8211b41ab6d2ccaafb407789ee/Utils.cpp#L51

This is the correct way to do it, I think this is the way we'll do it going forward. This issue will now track the conversion. I'll update your pr @rachitk

**Comment by jgkamat** [comment]
This issue is pretty complicated/diverse so I'm going to make the final few changes to it. Your commits will be part of #848, which will get merged once it gets tested/reviewed. Thanks for the contribution! :smile:
