### ISSUE TITLE
Create Configurable Points which can be used in testings and config plays

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#832]
Right now we have configurable constants which we use. This idea is to be able to set "Configurable points" on the config tab which basically contain X and Y poisitions, but can be set by clicking on the field. This could be generalizalble like our config system or just create like 4-8 set points like ConfigPoint1, ConfigPoint2, ConfigPoint3, and ConfigPoint4 which the plays can choose to use. 

Examples of use case is have an easily changed point that the play just moves a robot to. Points that can be set as the endpoints for lineup. It can take in a couple points like 4 and use them at waypoints to test pathplanning. We can set waypoints to test passing with different distances.

**Comment by justbuchanan** [comment]
Related to #425

**Comment by ashaw596** [comment]
Oh right! I could have sworn we had an issue, but I couldn't find it. That
ones better.

**Comment by jgkamat** [comment]
I really like this idea, although I don't know how hard it would be to implement (and whether it would be worth it).

**Comment by ashaw596** [comment]
Closed since pretty much duplicate of #425
