### ISSUE TITLE
Path Planning: merge SinglePlanRequest and PlanRequest

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#843]
They do basically the same thing, can they be merged into one class?

* [SinglePlanRequest](https://github.com/RoboJackets/robocup-software/blob/8ecdc354d77591ae8c0cce3ed3e62883d1bbf784/soccer/planning/SingleRobotPathPlanner.hpp#L16)
* [PlanRequest](https://github.com/RoboJackets/robocup-software/blob/8ecdc354d77591ae8c0cce3ed3e62883d1bbf784/soccer/planning/MultiRobotPathPlanner.hpp#L18)

**Comment by ashaw596** [comment]
That's the same thing @Jpfeltracco said! Eh. Probably???
