### ISSUE TITLE
The simulator bar should be disabled when running with real robots

### ISSUE THREAD

**Issue by chachmu** [RoboJackets/robocup-software#858]
The simulator menu contains several buttons that really only make sense when running make run-sim. The whole bar should be disabled when running soccer for real. The name of the bar can be found [here](https://github.com/RoboJackets/robocup-software/blob/d18e9b7fd56f42e1888e494064e0c264a9cceae8/soccer/ui/MainWindow.ui#L1946). QT items can be disabled with .setEnabled(false), like [this](https://github.com/RoboJackets/robocup-software/blob/d18e9b7fd56f42e1888e494064e0c264a9cceae8/soccer/MainWindow.cpp#L169) which should be done in the MainWindow constructer [here](https://github.com/RoboJackets/robocup-software/blob/2a5fed376542c2dcf5117fd26db1509e56e769fc/soccer/MainWindow.cpp#L45). Finally, the flag to check if the program is running in simulation is _processor->simluation().
<img width="700" alt="simulatormenu" src="https://cloud.githubusercontent.com/assets/14020373/21967216/b6681dbe-db50-11e6-93c0-2a34b227c6e9.png">

**Comment by jgkamat** [comment]
I'm not sure what part of the UI you're talking about, could you have a screenshot to the simulator bar?
