### ISSUE TITLE
Goalie Leaves the Goalie Zone when clearing a ball

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#863]
The normal robot rules (which are to stay out of the goalie zone) are being applied when the goalie enters the clearing state (once the ball enters the goalie zone). This is pretty bad, since the goalie runs away from the ball, leaving the goal open.

This might be a good beginner issue, but I'm not sure. Its very important though.

**Comment by jgkamat** [comment]
This is reproducable in the simulator, so you don't need actual robots to tackle this issue.

**Comment by zhangj150** [comment]
@jgkamat this should be demoted in importance.

**Comment by jgkamat** [comment]
@zhangj150 you should be invited now! Make sure to assign yourself to the issue you decide to work on (we discussed #591 in the meeting today)

**Comment by jgkamat** [comment]
Also this issue seems to only be reproducable in the stopped state (not in actual play) so this isn't as important as I thought.

**Comment by Jason27chan** [comment]
@jgkamat Can't seem to reproduce this issue. Is it fixed?

**Comment by jgkamat** [comment]
Yup, thanks for the bump. I think I fixed this at some point, I can't remember when.
