### ISSUE TITLE
Right Click kick at speed seems to be broken

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#865]
This seems to be a recent thing, it was working at comp last year. Probably needs a bisect.

Not sure if this isn't a duplicate, let me know if it is. 

When the right click kick ball occurs, the ball is first moved to a weird location, then kicked. This is most likely an issue with the simulator. The location where the ball moves to seems to depend on the initial placemnet of the ball and/or the strength/direction of the kick.

**Comment by petschekr** [comment]
Found the commit that introduced this: 6b4d87bf1ce8b473065df4a120b023b26fbf0ecd
