### ISSUE TITLE
When stopped, halting and re-stopping play causes robots to shift positions

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#866]
This seems kind of weird, and might be a red flag of some bigger problems in our role assignments.

When we stop play, halt, and restart play, no robots should move, because everything is in their correct places. However, robots often switch places for no apparent reason. This may be due to the ball obstacle for some reason, but this needs to be triaged to figure out the underlying cause.

**Comment by ashaw596** [comment]
Um, this might be an issue with our role requirements stuff too. This might be rather difficult.

**Comment by jcarn** [comment]
I'll check this out

**Comment by jcarn** [comment]
I found a way to do it but it is pretty hacky, basically forcing the stopped play's reqs to use the same robot they just used. This has some obvious issues, and I think the real issue is in how role_reqs is assigning cost to the reqs, but if we need a quick fix it exists.

**Comment by jgkamat** [comment]
I'd rather find the root cause, I'm worried that this is a symptom of a larger issue. This particular problem isn't too bad, so I don't think that it's worth it to add a specific workaround.

**Comment by jcarn** [comment]
The issue looks like role requirements are being given incorrect shell_ids. I found where this happens, and removing the line fixes the issue and doesn't seem like it affects anything else, but I want to talk to you about what might be going on.

**Comment by jgkamat** [comment]
Sounds like a plan, I'm glad you have a lead though! :tada:
