### ISSUE TITLE
When ball is close to defense, all robots try to clear the ball.

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#877]
This needs to be discussed, but I think it would be better for only one robot to clear the ball. Right now, both robots lunge for the ball, getting in each other's way, and in the end, both of them don't get it. 

Doing this might make us slightly more vulnerable (because we have less robots in between the ball and the goal.

This needs to be discussed, but I think that its better for us to send only the closest robot at this time.

Let me know before starting work on this so we can have a discussion.

**Comment by rk1998** [comment]
i'll try working on this. This may require some tweaks in mark behavior in submissive defender.
