### ISSUE TITLE
Drawing in Python fails

### ISSUE THREAD

**Issue by chachmu** [RoboJackets/robocup-software#878]
The system_state().draw_circle(... and other functions seem to not be properly drawing. I git bisected while testing to see if coordinated pass drew the triangle when passing and found that it stopped working here: 8e270b40ca13eef359f15122eb13703a2175463a although I can't immediately see anything wrong with the commit.

**Comment by JNeiger** [comment]
I found that you have to use the predefined names in the layers tab within the simulator. I think theres "Debug", "Info[1-4]" and a few others. 

See [here ](https://github.com/JNeiger/robocup-software/blob/adaptive_formation/soccer/gameplay/plays/testing/test_adaptive_formation_weights.py#L94)for an example

**Comment by chachmu** [comment]
The problem is that I don't think any of the code reflects that. As far as I can tell coordinated pass and Placement have always used that string as a description of what is being drawn. I don't know which is better but if we decide to stick with requiring the string to describe the layer we would need to change all of the places that the draw system is used incorrectly.

**Comment by JNeiger** [comment]
I think I found the fix. Good find on that commit, that helped a bunch
