### ISSUE TITLE
TODO our_kickoff.py

### ISSUE THREAD

**Issue by gtrosawa** [RoboJackets/robocup-software#928]
# TODO: verify that these values are right - I'm fuzzy on my matrix multiplication...

**Comment by JNeiger** [comment]
I think this one can be closed too. This references the array of positions to start on our kickoff. In the past, there were 4 positions to start, I assume this references the two additional ones which are just hardcoded position values.

**Comment by jgkamat** [comment]
We can never be sure if the matrixes will be correct tbh. Also I don't think there are any matricies here...

This is most likeley an invalid TODO.
