### ISSUE TITLE
FIXME less-precise LineKick submissive_goalie.py

### ISSUE THREAD

**Issue by gtrosawa** [RoboJackets/robocup-software#948]
# FIXME: what we really want is a less-precise LineKick
        #           this will require a Capture behavior that doesn't wait for the ball to stop
        kick = skills.pivot_kick.PivotKick()

**Comment by jgkamat** [comment]
#911 is relevant to this, but we need to test the new line kick A LOT before we commit it to the goalie. Maybe we can do this in the far future, but this will remain a todo until then.
