### ISSUE TITLE
Add one playbook to gitignore

### ISSUE THREAD

**Issue by jcarn** [RoboJackets/robocup-software#967]
A lot of testing involves running one play repeatedly, and often requires restarting every time. It is quicker to set up a playbook with that play selected and designate as the playbook to use. However, it is annoying to deal with the git part of changing a file you don't want to commit. Could we create a playbook like testing_playbook that we add the the ignore?

**Comment by jgkamat** [comment]
Maybe we could just have soccer start with a personal_playbook.pbk file by default, and if it dosen't exist, nothing get's loaded. It would be hard to advertise and document though...

We could then add that playbook file to the gitignore, so people can add it if they want (and it won't get committed).

**Comment by jcarn** [comment]
This could be a good issue for Fall next year, unless I get really bored I'll probably let it sit until then

**Comment by jgkamat** [comment]
Ok I'm wasting a bunch of time on this so this is happening now.
