### ISSUE TITLE
Split 2D overlay from Adaptive Formation into it own function

### ISSUE THREAD

**Issue by JNeiger** [RoboJackets/robocup-software#973]
See [here](https://github.com/RoboJackets/robocup-software/pull/958#discussion_r112817441)

**Comment by JNeiger** [comment]
Where would be a good place to put this? I can't think of a folder anywhere where this would fit in nicely.

**Comment by jgkamat** [comment]
I would agree with you that there's no good place to put this right now, how about we make a new module for it? We could call it visualization, or misc?

If we wanted to avoid making another module for some reason though, the best place (in my opinion) would be in ./soccer/gameplay/evaluation.

**Comment by JNeiger** [comment]
This could also be implemented into the play class itself. It might be nice to see in the simulator when we run it on real robots or something.
