### ISSUE TITLE
Allow subfolders in the Play selection window

### ISSUE THREAD

**Issue by JNeiger** [RoboJackets/robocup-software#975]
Only one level of folders are available in the current setup, it would be nice to be able to have subfolders for some of the more complicated plays and such.

**Comment by CollinAvidano** [comment]
This already exists. After friggin so much time testing Jay let me know that the only thing you need to do is create a sub directory and add an _init_.py file to the subdirectory.

**Comment by jgkamat** [comment]
#justpythonthings
