### ISSUE TITLE
During theirRestart, marking is not assigning bots correctly to mark enemies.

### ISSUE THREAD

**Issue by krispreza** [RoboJackets/robocup-software#976]
Seems to work correctly for 1 bot however the other two bots running marking are inactive.

**Comment by jgkamat** [comment]
I'm going to take this since it's pretty important to have done by comp...

**Comment by jgkamat** [comment]
Seems like marking works fine if the enemy robots are close to the ball, but in certain scenarios (if their receivers are far away) this leaves 3 of our robots unmovable.
