### ISSUE TITLE
Evalute whether we should convert from doxygen docs to python official docstrings

### ISSUE THREAD

**Issue by jcarn** [RoboJackets/robocup-software#978]
A lot of plugins python docstrings to provide information about imported modules, but right now we don't have any afaik. We should add these, it would be a great way to learn the codebase!

**Comment by jgkamat** [comment]
This is actually an interesting point that we might want to consider in more detail. Right now, our docs are generated from `##` at the top of methods, but we should really be taking advantage of the official python documentation so we can view it in the interpreter as well as online. We need to see if doxygen supports this style of documentation though, and if it does, we probably should convert everything to use the official docstring style.

**Comment by kylestach** [comment]
It looks like doxygen does support docstrings, although it does not support special doxygen commands `\something` inside of them. It doesn't look like we actually use those anywhere though, so we should be good to switch.
