### ISSUE TITLE
MOTION CONTROL

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#98]
We need to suck it up and do some actual math and control theory, we've had crap motion control for too long.

**Comment by justbuchanan** [comment]
Here's a link to the new motors we'll be using on the Maxon website: http://www.maxonmotorusa.com/maxon/view/product/motor/ecmotor/ecflat/ecflat45/339285?download=show#.

**Comment by justbuchanan** [comment]
I found a good writeup on modeling brushless DC (BLCD) motors: http://www.ijaestonline.com/admin/post_image/1387172494_State-Space_Based_Simulink_Modeling_of_BLDC_Motor_and_its_Speed_Control.pdf.

On page 361 (only a few pages in), they derive and show the state equation for the motor, which will be helpful to us at some point when we incorporate that into the control setup.

**Comment by justbuchanan** [comment]
I finished the dynamics derivation writeup, which can be found on [overleaf](https://www.overleaf.com/read/hznhwffjtrhc).

Next steps:
- [ ] Setup SimuLink simulation for the model
- [ ] Linearize dynamics model and apply LQR to it
- [ ] Tune LQR weights

**Comment by justbuchanan** [comment]
I've got a pretty sweet simulation setup in MATLAB / Simulink on the [modeling branch](https://github.com/RoboJackets/robocup-software/tree/modeling/modeling).  It needs a little work and tuning, but the design is mostly done.

Todo:
- [ ] Add latency to the simulation
- [ ] Tune LQR weights
- [ ] Tune PID weights
- [ ] Test rotational velocity commands - there may be some issues here...
- [ ] Writeup the dynamics derivation and an intro to LQR
- [ ] Rewrite in C++ for the simulator and robot firmware
    - [ ] Use integers because floats aren't a thing on the MBED :(
    - [ ] Figure out discrete time vs continuous time

**Comment by justbuchanan** [comment]
I've got this almost completed, it should be done by the end of the weekend.

**Comment by JNeiger** [comment]
@justbuchanan Did you ever verify the accuracy of the model you made in #312?

**Comment by barulicm** [comment]
@JNeiger I don't remember if he had any methodology queued up for verifying it, but I do remember the model having at least a handful of properties that were specific to the physical robot design (ie center of mass). So at the very least, it would need to be updated based on the current robot design.

**Comment by justbuchanan** [comment]
Yes, the parameters will need adjusting for the new robots, but that should be easy to do for the most part. A couple of the parameters, such as wheel friction, will be a bit tougher to get right since they may vary significantly between wheels and between robots. You may be able to get away with using one value for all robots/wheels, but ideally that would be tuned on a per-wheel basis.

I never did run the LQR controller on the robots since I ran out of time before competition, but the results I was getting from the matlab simulation seemed promising. I'm not entirely sure how to go about verifying the model other than doing some basic sanity checks of sample inputs/outputs (which I did) and getting it actually running on the robots.

I had a C++ version of the LQR controller implemented in https://github.com/RoboJackets/robocup-software/pull/322, but I ran out of time and didn't merge it. It would take some work to get that synced with the latest changes and repo splits, but it should provide a good starting point if you're looking to get this working.

Let me know if you have any other questions though, I'd be happy to help.

**Comment by JNeiger** [comment]
Sounds good. 

I think my plan right now is to edit the model a little bit to better reflect our current cascading PID approach to see if there are any "simple" improvements we can make to the controllers to improve performance in the short term.

In the long term, I'm going to try and get the LQR implementation updated and working on real robots. I might wait until after spring semester to start so I can finish a couple controls classes though.

**Comment by JNeiger** [comment]
Closing in favor of #1213
