### ISSUE TITLE
Coordinated Pass Gets Stuck Preparing

### ISSUE THREAD

**Issue by jcarn** [RoboJackets/robocup-software#984]
I don't know what causes this yet, currently looking into it. Basically what happens is that the ball is kicked while the receiver is in aligned state, and the receiver does not transition into receiving state.

**Comment by jgkamat** [comment]
Yup, I've definetly seen this too. It's an edge case for sure. If you could find out why that would be :heart:

**Comment by jgkamat** [comment]
Also if you think it's not a problem with the play itself: #907

**Comment by jcarn** [comment]
I'm pretty sure this is a problem with the play, since I only found it when I deliberately caused in test_coordinated_pass and then also when I misused the play in behavior sequence
