### ISSUE TITLE
Verify/Implement ball placement both when placing and when standing by

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#985]
Our current stopped play will conflict with this rule:

![capture](https://user-images.githubusercontent.com/4349709/26935875-fac4934c-4c21-11e7-941b-33d702c3b721.PNG)

We should probably:

1) go into line up when a ball placment is issued to the opposing team
2) Implement #676 

@chachmu do you think you could take this?

**Comment by chachmu** [comment]
Currently our robots just freeze in place if the other team is supposed to place the ball. I can fix that and I think I will also need to change how exiting the ball placement state works since they no longer specify how play is restarted after the placement.

**Comment by chachmu** [comment]
@jgkamat Do you know where the SSL coordinate system for the field is defined? I want to find an official source so I know I get it right this time but it is proving surprisingly difficult to find.

**Comment by jgkamat** [comment]
The docs seem surprising hard to figure out... [here it says they use 'ssl-vision' coordinates](https://github.com/RoboCup-SSL/ssl-refbox/blob/ead58770b032ca380987cb9e1200b04b0d1db0f3/rcon.proto#L56-L62)

I'm not sure what that means, but I think that means that (0,0) is the 'bottom of the field'. One teams goal is the 'bottom' in SSL Vision (and we flip it using +/- defense internally). We probably want to get the raw, unflipped coordinates from ssl-vision.

**Comment by chachmu** [comment]
Yeah I need to find what format the SSL vision system uses because I am pretty sure last year the x and y coordinates were flipped too. I think it was something like we say that x is the width of the field and y is the length but SSL has it opposite of that.
